### ISSUE TITLE
pb2nc cycleless file processing mode

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#105]
Bug and Enhancement:

Re-Confirm This Bug:
The current mechanism to process a set of input files and rename the output files
to the input_filename.nc doesn't appear to work. I had to put temporary change in 
place in order to get this work.  I requires further analysis and a more proper solution
on my part.

Note: There is also a dependency on the PREPBUFR_DIR_REGEX = .*\/rap\/(2[0-9]{9}
required to having a cycle pattern group defined when trying to run in this
'cycleless' input file processing mode.

Enhancement:
Add a switch (aka a conf variable) that would just turn on the ability to process an input directory,
and write output by just appending .nc to filename. regardless of any cycle YMD related conf
variable settings etc .... It would be an override.
- This processing of input would support the subdirs, and regex templates (dir, and filename).

If the input path defined in the conf  has subdirectories. ...
PREPBUFR_DATA_DIR = /blahdir1/blahdir2

lets say blahdir2/ has additional (subdirectories) ....

consider:
This is straight forward for a single directory ... OUTPUT_DIR/output_files.nc

When processing (subdirectories), the subdirectories will be added
to the output path, ie. written to SOME_CONF_OUTPUT_DIR/(subdirectories)/output_files.nc

**Comment by georgemccabe** [comment]
I am not sure I fully understand the issue here, but the refactor to pb2nc and point_stat allows processing of files without cycles in their name. Testing this use case with the new version would prove if the fix has solved this issue or not...
