### ISSUE TITLE
Fix installation instructions in User's Guide

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1067]
## Describe the Problem ##

The current installation instructions tell users to use the scripts in the build_components directory to install MET and other METplus components:

https://metplus.readthedocs.io/en/v4.0.0/Users_Guide/installation.html#build-components-and-using-manage-externals

However, the script does not work and produces many errors. There will be a separate issue to fix the scripts, but in the meantime we should update the documentation to direct users to download the latest release tarfile and refer to the installation instructions in chapter 2 of the MET User's Guide instead of using these scripts.

These changes should be applied to the main_v4.0 and develop branches.

A recent GitHub Discussions question brought this to attention: https://github.com/dtcenter/METplus/discussions/1059

The comments of this discussion include info provided to the user to get MET installed that can be used as a reference to update the documentation.

### Relevant Deadlines ###
ASAP

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Organization** level **Project** for support of the current coordinated release
- [X] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
One line change in installation.rst. Pushed to develop and main_v4.0

**Comment by jprestop** [comment]
@fisherhucar 
This issue was closed, but it is still confusing users ([Discussion #1149](https://github.com/dtcenter/METplus/discussions/1149)). It does not appear that documentation was added to direct users to download the latest release tarfile and refer to the installation instructions in chapter 2 of the MET User's Guide instead of using these scripts. Given the continued confusion and problems with manage_externals, it seems we should potentially remove the “Build_components and using manage_externals” section entirely (adding it back once it's ready for use) in favor of the directing users to download the latest release tarfile and referring the users to the installation instructions in chapter 2 of the MET User's Guide instead as the issue describes. When you're ready for a pull request, feel free to assign it to me or @georgemccabe.  Thanks!

**Comment by jprestop** [comment]
@fisherhucar
@georgemccabe and I had some time to work on this today, so this work is now complete.  I'll submit a pull request now for develop and main.
