### ISSUE TITLE
Cyclone plotter symbols not connected by lines

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#115]
The "caropy" dependent version of the plot no longer renders with the '+' and  'o' symbols connected by a line.  The matplotlib command for drawing a line plot over the scatter plot is not working.  A work-around is needed.

**Comment by georgemccabe** [comment]
@bikegeek  was this completed in another issue? If so, could you reference that issue and close this one?

**Comment by bikegeek** [comment]
Fixed.  refer to https://github.com/dtcenter/METplus/pull/804
