### ISSUE TITLE
Installation of MetPlus on Windows 10 WSL2 & AWS Cloud 

### ISSUE THREAD

**Issue by marstonsward** [dtcenter/METplus#1167]
Hi,

# Use Case 
My company would like to begin using MetPlus. I would like to first test it on one of our windows PC using WSL2. Later on our cloud team would like to move MetPlus to the cloud. I see that there is a docker image and I wondering if it can be used as a devcontainer in VS Code - if anyone has experience with that. 

# Use Case Name and Category 
Installation in new environments

# Input Data ###
Synthetic vertically integrated liquid and dBZ

**Comment by JohnHalleyGotway** [comment]
Converting this support question from an issue to a discussion. Please post questions as [new discussions](https://github.com/dtcenter/METplus/discussions/new).
