### ISSUE TITLE
Remove public-facing access to outdated use case categories (Cryosphere, marine_and_coastal)

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1226]
## Describe the Task ##
During the completion of issue #1200, it was decided that the data to the use case categories that marine_and_cryosphere was replacing should not be removed right away. While adding the new use case category (effectively duplicating the existing use cases) and removing the old documentation, references in the User's Guide, etc. would be straight-forward, any work that was being done on the branch involving the old use case categories, and any existing branches at all, would experience significant unit test changes.

In order to lessen the impact, the data for the outdated use case categories was kept in place.

This github issue serves as a reminder that in the final code release, we need to make the old data tarballs on Mohawk "hidden". Hopefully we can keep a copy of the data for backup needs, but it should not be accessible via METplus repo.

### Time Estimate ###
*Estimate the amount of work required here.*
~1-2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Release of METplus v4.1

### Funding Source ###
None

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This has already been completed. The v4.1 directory does not contain the old tar files for marine_and_coastal and cryosphere categories. The v4.0 directory still does because this reflects the categories for that release, so the old data structure is still available if we need to review it for any reason.
