### ISSUE TITLE
Bugfix: Add support for the {custom} loop string in the MODEL config variable

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1382]
## Describe the Problem ##

During the creation of a use case that utilized the custom looping feature (e.g. POINT_STAT_CUSTOM_LOOP_LIST), it was discovered that {custom} and {custom?fmt=%s} were not available options as MODEL variable input (e.g. MODEL = {custom?fmt=%s} ). Setting it in this manner would make METplus error out:
```

raise KeyError(key)
KeyError: 'custom?fmt=%s'
```
As provided below, the preferred (and working) method to avoid such issues would be to utilize multiple instances of the tool. 
So instead of having one call to the desired tool in the PROCESSES list and multiple entries in the tools' custom loop list, make multiple instances to the desired tool and set each variable, including MODEL, individually for each tool instance.

### Expected Behavior ###
Even with the desired alternative, it would be useful if each call to a tool with a custom loop list could utilize the custom string inside the output files for the MODEL variable. This is especially true if the end goal is for ingestion in METviewer, where column values become critical for accurate graph creation.

### Environment ###
Describe your runtime environment:
*1. Machine: kiowa
*2. OS: Linux
*3. METplus 4.1.0beta5

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. create custom loop list for a given tool
*2. set MODEL to {custom}
*3. Run configuration file
*4. See error*

There is a use case being created on Kiowa that revealed this issue that I can point an assigned engineer to (Ptype)

### Relevant Deadlines ###
None, this does not impact the completion of the use case

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
In my opinion we shouldn't fix this behavior. Using an instance identifier is the preferred approach to setting config variables differently for different instances of a wrapper. Using {custom} is supported in filename templates. Ensuring that it will work with every config variable is not maintainable.

Instead of configuring the following:

```
[config]
PROCESS_LIST = GridStat
GRID_STAT_CUSTOM_LOOP_LIST = first_model, second_model
MODEL = {custom}
```

you can accomplish the desired behavior by setting:

```
[config]
PROCESS_LIST = GridStat, GridStat(second)

MODEL = first_model

[second]
MODEL = second_model
```

**Comment by georgemccabe** [comment]
Looking into this closer, I discovered that there is indeed a bug in the logic to handle the deprecated MODEL env var (the current wrapped MET config files reference METPLUS_MODEL but MODEL is still supported for very old config files). I will make the fix.
