### ISSUE TITLE
Add the "desc" MET 8.0 config entry name as environment variable to METplus

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#139]
Requested by JohnHG (entered by JimF)
Add the "desc" MET 8.0 config entry as and environment variable to METplus

Reference MET_INSTALL_DIR/share/met/config/README

Discuss this ticket: ! ?
Add "desc" .... for each of the METplus use cases. ? Not sure.
Note: Though this issue is trivial to implement ... it is extensive and touches 
just about every wrapper and config file .... that is ... it is duplicated everywhere ...
We should discuss this ... 

This ticket it to:
Add the "desc" MET 8.0 config entry name as an environment variable
to the METplus MET config files with the ability to set the value in 
the METplus configuration file and set it as an environment variable
in the METplus runtime ... that is, export it to the environment ... 

Note:
At the very least, "desc" will be have been add as a entry name to the METplus MET
config files via issue #138, but just not as an environment variable which is what this
ticket is about.

**Comment by jimfrimel** [comment]
From the MET_INSTALL_DIR/share/met/config/README

//
// The "desc" entry specifies a user-specified description for each verification
// task.  This string is written to the DESC column of the ASCII output
// generated.  It may be set separately in each "obs.field" verification task
// entry or simply once at the top level of the configuration file.  If you're
// verifying the same field multiple times with different quality control
// flags, you should choose description strings (no whitespace) to distinguish
// between their output.
// e.g. desc = "QC_9";
//
desc = "NA";

**Comment by georgemccabe** [comment]
desc in all wrappers is now supported via METplus config. Implemented in this pull request: https://github.com/dtcenter/METplus/pull/756
