### ISSUE TITLE
Bugfix: Set Point2Grid -adp and -qc arguments properly

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1623]
This came up in Discussion #1619

## Describe the Problem ##
The value set for -qc or -adp are not actually added to the command.
```
        if self.c_dict['QC_FLAGS']:
            self.args.append("-qc")

        if self.c_dict['ADP']:
            self.args.append("-adp")
```

### Expected Behavior ###
The value set for POINT2GRID_QC_FLAGS and/or POINT2GRID_ADP should be added to the command.

```
        if self.c_dict['QC_FLAGS']:
            self.args.append(f"-qc {self.c_dict['QC_FLAGS']}")

        if self.c_dict['ADP']:
            self.args.append(f"-adp {self.c_dict['ADP']}")
```

Also review the rest of the command line arguments to ensure that they are set properly.

### Environment ###
Any

### To Reproduce ###
Run Point2Grid wrapper with POINT2GRID_QC_FLAGS and/or POINT2GRID_ADP set to reproduce the error.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by PerryShafran-NOAA** [comment]
Hi, all.  Can we get an update on this issue?  It looks like it is just about done.  When can I test it at EMC?

**Comment by georgemccabe** [comment]
Hi @PerryShafran-NOAA, this fix was included in the METplus 5.0.0-beta1 release which is available on Hera, Jet, and Orion. It looks like this issue was not closed, because it has not yet been added so it will be available in the next bugfix release, which would be v4.1.3. Is this something you need available as a bugfix to v4.1 or is using v5.0.0-beta1 sufficient?

**Comment by PerryShafran-NOAA** [comment]
Yes, would be great to have it as a bugfix to 4.1.  And I wasn't entirely sure if you could post it to Acorn, the WCOSS2 test machine, which I am assuming that you are able to do so.

**Comment by georgemccabe** [comment]
OK, I can create the bugfix release but I don't have access to WCOSS2. I can ask someone else who has access to install it there.

It looks like the fix was added to the main_v4.1 branch in commit https://github.com/dtcenter/METplus/commit/c90be365908f89096fcff921bc7b598911452963 so the bugfix release should be ready to cut.

**Comment by PerryShafran-NOAA** [comment]
At least the bugfix can help us develop the code, and then we'll be ready to go when METplus 5.0.0 is released later this year.  I *think* you folks have access to Acorn and can post code there.  Let me ensure that is the case first before you or anyone at DTC does anything.

**Comment by jprestop** [comment]
My understanding was that Acorn was to be used to test installations of the METplus components, but not to test the functionality of the METplus components. @AliciaBentley-NOAA, can you please confirm?

**Comment by AliciaBentley-NOAA** [comment]
That is my understanding too, @jprestop. Perhaps the functionality of METplus components could be tested on Hera, and METplus installations could be built/tested on Acorn (prior to NCO installing them on WCOSS2)?

**Comment by jprestop** [comment]
That seems like a good way to proceed @AliciaBentley-NOAA.  @PerryShafran-NOAA, would you like the bugfix version on Hera or would you prefer to use the 5.0.0-beta1 version on Hera (or soon to be 5.0.0-beta2 version on Hera)?

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @jprestop I have to admit not to using Hera very often and I foresee some issues as there is a lot of data that needs to be moved between machines, and scripts needing to be modified for Hera.  However, if I cannot test the functionality on Acorn, then I can make it work for Hera.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @jprestop I believe that data would need to be moved from WCOSS2 to Acorn for testing to be done there as well. 

I'm not sure how heavy a lift it will be for scripts to be modified to work on Hera, but I hope it wouldn't be too much (at the module load and directory level, perhaps). Deanna and Mallory use METplus on Hera currently, and they can tell you how to load it on Hera, etc. This is also be on the DTC webpage. If it's too much to ask, please let us know, and we can consider having you move data to Acorn instead and asking Julie to install the bugfix version on Acorn as well.

**Comment by PerryShafran-NOAA** [comment]
I'll test to see what kind of a lift it would be to move to Hera - I always overestimate the work that I might need.  If it takes time, then I'll get back to you.

Either bugfix or beta version would be fine.  I suspect if it would work for one, it would work for the other.
