### ISSUE TITLE
Cleanup Logging

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#180]
We should add a log INFO statement to note that METplus execution has completed so it is clear that the run is finished.

**Comment by bikegeek** [comment]
I wonder if we should solicit log file format requests from end
users...just a thought.

-Min
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by georgemccabe** [comment]
I cleaned up logs in the following files and pushed the changes to the feature_180_log_cleanup branch:

command_builder.py
command_runner.py
compare_gridded_wrapper.py
config_launcher.py
config_metplus.py
cyclone_plotter_wrapper.py
extract_tiles_wrapper.py
feature_util.py
gempak_to_cf_wrapper.py
met_util.py
mode_wrapper.py
mtd_wrapper.py
reformat_gridded_wrapper.py
regrid_data_plane_wrapper.py
usage_wrapper.py

We still need to review the following:
series_by_init_wrapper.py
series_by_lead_wrapper.py
stat_analysis_wrapper.py
string_template_substitution.py
task_info.py
tcmpr_plotter_wrapper.py
tc_pairs_wrapper.py
tc_stat_wrapper.py
wavelet_stat_wrapper.py

**Comment by georgemccabe** [comment]
I think this can be closed. We have addressed the concerns in this issue by reviewing/enhancing logging with other development over the years. If other logging enhancements are desired, we should create a new issue or issues that address that specific need.
