### ISSUE TITLE
Create Python embedding script for COCORAHS use case

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1832]
## Describe the Task ##
This is a sub issue to track progress on the Python script that will need to be created to allow development of #1828 
Input data has been provided by EMC (on Hera, under /scratch2/NCEPDEV/ovp/Logan.Dawson/com/cocorahs/*), which is in a csv format.

### Time Estimate ###
3-5 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2773542

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
After reviewing the contents of the CoCoRaHS file, the solution to an ASCII2NC Python Embedding script may not be as straight forward as utilizing the existing read_ascii_point.py. This is due to the contents and layout of the file; in order that each variable (TotalPrecipAmt | NewSnowDepth | NewSnowSWE | TotalSnowDepth | TotalSnowSWE) be passed to the final netCDF, several new lists will have to be implemented as they do not appear in the original file These include a `var_name` list, `message_type`, `elevation`, `level`, `height`, and `qc_string`. 

For clarification before any more work continues, can @PerryShafran-NOAA or @LoganDawson-NOAA state what variables are of interest from the CoCoRaHS file from the list above?

**Comment by PerryShafran-NOAA** [comment]
@j-opatz I'm only worried about the precipitation, and I am not verifying snow.  So it would be TotalPrecipAmt.  

Perry

**Comment by j-opatz** [comment]
Development is nearly finished, but there remains one sticking point:

In the observation values, there are records of trace precipitation, noted "T". These are not recognized values in MET, and are causing an issue during the handling process of ASCII2NC.

@PerryShafran-NOAA and @LoganDawson-NOAA how should trace "T" records be dealt with? Should they be set equal to something (NAN, 0, etc.)? Should they be skipped completely? When I have that answer, the script should come together in < a day.

**Comment by LoganDawson-NOAA** [comment]
@j-opatz the reports of Trace precipitation can be read in and set to 0. They're still legitimate records of less than 0.01" of precip, so it makes sense to include them.

Thanks for asking about this to make sure we come to a good agreement on how those reports should be handled.

**Comment by j-opatz** [comment]
Script is now successfully pulling in CoCoRaHS file and passing to ASCII2NC tool
