### ISSUE TITLE
Add support in extract_tiles.py for varied data types

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2]
Support for other data: WRF, MRMS radar, data that is netCDF (other than just GRIB 2); can we also support GRIB1?

**Comment by bikegeek** [comment]
John, is this still relevant????

**Comment by georgemccabe** [comment]
I believe this issue can be closed. The ExtractTiles wrapper uses RegridDataPlane to create the tiles, so it should support any input file type that is supported by MET. If we discover there is a specific data format that is unable to be read by the tool, we should create a new issue to add support for that data.
