### ISSUE TITLE
Create Sample HRRR ensemble Valid Time use cast test data set. 

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#200]
Locate, Prune GRIB files  and get test data packaged to test the ensemble stat
looping by Valid Time use case.  

2 maybe 3 Valid Times should be sufficient.

SEE if we can locate the data to extend the current INIT TIME  test data to the next cycle, that way we can utilize the current ensemble data test case to be used for testing init time and valid time, thereby minimizing the increase in ensemble test data space.  If we can't,
locate the next cycle, it would be worth creating an new data set that can be used
for both init time and valid time testing.

REFER TO CLOSED ISSUE: #193 for information/commands on HRRR ensemble data
sizes and  on reducing grib file size and for the current variables setup for testing
the ensemble use case.

ie.
`wgrib2 -s wrfprs_conus_mem0001_00.grib2 | egrep '(:TMP:2 m|:DPT:2 m|:UGRD:10 m|:VGRD:10 m|:WIND:10 m)' | wgrib2 -i wrfprs_conus_mem0001_00.grib2 -grib var5.grib2`

**Comment by fentoad72** [comment]
@JohnHalleyGotway is this issue still an issue?  Or can it be closed?

**Comment by georgemccabe** [comment]
Will not complete.
