### ISSUE TITLE
Bugfix: PointStat -obs_valid_beg/end arguments not set properly

### ISSUE THREAD

**Issue by mrinalbiswas** [dtcenter/METplus#2137]
*Replace italics below with details for this issue.*

## Describe the Problem ##
I am working on a use case that uses Point-Stat. I want Point-Stat to include all data that are provided in the POINT_STAT_OBS_VALID_BEG and POINT_STAT_OBS_VALID_END env variables that is present in the conf file. When POINT_STAT_OBS_VALID_BEG and POINT_STAT_OBS_VALID_END are set, they DO NOT appear in the -obs_valid_beg/end command line arguments for Point-Stat.

### Expected Behavior ###
The time window should appear when METplus is run with the command builder. 

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Hi @mrinalbiswas, thank you for discovering this bug. It looks like the logic was broken in a previous refactor. I can fix this and update the unit tests to ensure that it is set properly going forward.

Is applying this fix for the upcoming METplus 5.1.0 release acceptable, or do you need a bugfix applied to 5.0?

**Comment by jprestop** [comment]
@georgemccabe @JohnHalleyGotway Any idea if this bug will impact EMC?

**Comment by mrinalbiswas** [comment]
@georgemccabe I would leave it to the release committee, because I am not sure how many use cases will be impacted. I know this will be useful to our CLASP use case.

**Comment by georgemccabe** [comment]
If this functionality was used by any EMC use cases, then I think this would have come to our attention earlier. I suppose it is possible that it went unnoticed. It looks like this logic broke between METplus 3.0 and 3.1.

> @georgemccabe @JohnHalleyGotway Any idea if this bug will impact EMC?

**Comment by jprestop** [comment]
Thanks @georgemccabe.  To be safe, I'll tag @AliciaBentley-NOAA and @LoganDawson-NOAA so they are aware.
