### ISSUE TITLE
New Use Case: PANDA-C x6

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#2188]
## Describe the New Use Case ##
This is a continuation of #1686 which created several new use cases but did not place them into the repository.

The decision has been made to now include them, which will require creating documentation, cleaning up the configuration files and python script, and providing input data.

### Use Case Name and Category ###
There were 9 use cases created in the initial issue, with 6 being selected to merge into the repository. The following are the respective names. All will reside in the Air quality and composition category:
MPAS to SATCORPS: GridStat_fcstMPAS_obsSATCORPS_lowAndTotalCloudFrac
GFS to SATCORPS: GridStat_fcstGFS_obsSATCORPS_cloudTopPressAndTemp
MPAS to MERRA2: GridStat_fcstMPAS_obsMERRA2_lowAndTotalCloudFrac
GFS to MERRA2: GridStat_fcstGFS_obsMERRA2_lowAndTotalCloudFrac
MPAS to ERA5: GridStat_fcstMPAS_obsERA5_cloudBaseHgt
GFS to ERA5: GridStat_fcstGFS_obsERA5_lowAndTotalCloudFrac

### Input Data ###
File sizes are listed for each source:
GFS: ~530MB
MPAS: ~400MB
SATCORPS: ~103MB
MERRA2: ~213MB
ERA5: ~10MB

If a use case can utilize the same data as another use case, that will be pursued to try and minimize data size.

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
2.5 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021 (20 hours only)

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Reopening this issue to enable the use cases to run in the automated tests without running out of memory.
