### ISSUE TITLE
Bugfix: Allow spaces for complex categorical thresholds

### ISSUE THREAD

**Issue by melissaOu** [dtcenter/METplus#2189]
Request for the Grid Stat category thresholds for forecast and observations to allow spaces between logicals, similar to Series Analysis. The below 
BOTH_GRID_STAT_VAR1_THRESH =  lt-0.5, gt-0.5 && lt0.5, gt0.5
results in an error of:
ERROR: Could not process OBS_VAR1 variables: Invalid threshold supplied (same for FCST)
metplus (command_builder.py:257) ERROR: (compare_gridded_wrapper.py:153) No input fields were specified. You must set [FCST/OBS]VAR<n>[NAME/LEVELS].
the METPlus documentation has this for FCST_VAR_THRESH Set this to a comma-separated list of threshold values to use in the comparison. Each of these values must begin with a comparison operator (>, >=, =, ==, !=, <, <=, gt, ge, eq, ne, lt, or le).

Removing spaces between the values and '&&' works, though (BOTH_GRID_STAT_VAR1_THRESH =  lt-0.5, gt-0.5&&lt0.5, gt0.5).

Series analysis runs properly when spaces are between the logicals and inequalities so the behavior should match. Also, the resulting error of "Set this to a comma-separated list of threshold values to use in the comparison. Each of these values must begin with a comparison operator (>, >=, =, ==, !=, <, <=, gt, ge, eq, ne, lt, or le)." did not reflect this issue but fixing this would make the error make more sense.
 

### Relevant Deadlines ###
5.1.0 and 5.0.2

### Funding Source ###
2700044

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Organization** level **Project** for support of the current coordinated release
- [X] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [X] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [X] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [X] Fix the bug and test your changes.
- [X] Add/update log messages for easier debugging.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Push local changes to GitHub.
- [x] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Hi @melissaOu, thank you for bring this to our attention. I ran a quick test and confirmed that I can recreate this bug. Spaces in a list of thresholds are handled properly around each item and commas, but they are not handled properly in complex thresholds like `gt-0.5 && lt0.5`. I will fix this for the upcoming METplus 5.1.0 release which is scheduled for late June.

Do you also need a bugfix to be applied to METplus 5.0?

**Comment by melissaOu** [comment]
Hi George, glad you could reproduce it and thanks for working on this. We
would prefer this be implemented in 5.0 as well but if its a lot of extra
work it is not a big deal, we should be ok with getting the next release.

Thanks,
Melissa

**Comment by georgemccabe** [comment]
Hi @melissaOu, it is not difficult to implement this bugfix for 5.0. I have made the changes in the main_v5.0 branch, but have not yet cut the METplus 5.0.2 bugfix release. Is there a specific machine that you need this installed on?

**Comment by melissaOu** [comment]
Hi George,
We have a volume thats mounted that has MET and each person using this at
CPC executes the MET install sitting on this volume but it runs on each
person's machine. Is there a reason why you are asking this? Just trying to
make sure we understand.

Thanks
Melissa

**Comment by georgemccabe** [comment]
@jprestop is the METplus developer who typically installs releases on certain NOAA machines, but she is out on PTO for the next several weeks. Another METplus developer could take care of the install in her absence if they have access to the machine where it will be installed.

**Comment by melissaOu** [comment]
Hi George, we do all our installs in house, it is not e.g. a centralized
server so as long as there is a release we will be able to install or
update our own version.

Thank you!
Melissa

**Comment by georgemccabe** [comment]
Hi @melissaOu, the METplus 5.0.2 bugfix release is now available here: https://github.com/dtcenter/METplus/releases/tag/v5.0.2

**Comment by melissaOu** [comment]
Great thank you!
