### ISSUE TITLE
Improve Contributor's Guide during When working on #2198

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#2207]
When working on #2198, a few items were identified that should be changed. This issue is to document those items and have them approved.

## Describe the Task ##
*Provide a description of the task here.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
1) Here: https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#open-a-pull-request, it says "a webpage with four gray buttons should appear". However, it appears there are only two gray buttons. I do not see the "base repository" and "head repository" buttons, but rather only "base button" and "compare button".

2) This section was confusing. I copied my env bash file to mohawk as myself to my own area. When I `runas met_test`, I couldn't source the file in my own area, and `met_test` does not appear to have write privileges in `/d2/projects/METplus/METplus_Data_Staging`. Maybe this is by design but we can probably add a little to this section to make it clearer.

3) In this section: https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#add-volume-mount-directories-file, I missed this comment the first few times:
> Update the entry for the new tarball if the mounting point has changed (unlikely) or add a new entry if adding a new sample data tarfile.

It might be nice to add a sphinx `note` or something specifically noting that if you are adding new sample data for a new category that doesn't exist already, additional steps are needed to edit the file to make it more obvious.

**Comment by georgemccabe** [comment]
Here are some of my notes for updates to add use cases contrib guide:

8.7.1.5. -- step after copy -- there is 3rd condition for new category
  ls -lh sample_data-${METPLUS_USE_CASE_CATEGORY}*
  ls: cannot access 'sample_data-land_surface*': No such file or directory
  do nothing if this is the case!

8.5.2.11 Add volume_mount_directories - make more clear to add entry if adding the first use case in a new model applications category

**Comment by georgemccabe** [comment]
@DanielAdriaansen, regarding:
> 1. Here: [metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#open-a-pull-request](https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#open-a-pull-request), it says "a webpage with four gray buttons should appear". However, it appears there are only two gray buttons. I do not see the "base repository" and "head repository" buttons, but rather only "base button" and "compare button".

If you go to dtcenter/METplus, there are 2 grey buttons, but if you navigate to a fork e.g. georgemccabe/METplus, as the instructions describe, you will see 4 grey buttons.

**Comment by DanielAdriaansen** [comment]
> @DanielAdriaansen, regarding:
> 
> > 1. Here: [metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#open-a-pull-request](https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#open-a-pull-request), it says "a webpage with four gray buttons should appear". However, it appears there are only two gray buttons. I do not see the "base repository" and "head repository" buttons, but rather only "base button" and "compare button".
> 
> If you go to dtcenter/METplus, there are 2 grey buttons, but if you navigate to a fork e.g. georgemccabe/METplus, as the instructions describe, you will see 4 grey buttons.

Fair, however earlier here: https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#fork-the-dtcenter-metplus-repository it advises those with write privileges to skip creating a fork. In this case, the user I was helping had write privileges so they did not have a fork and asked me specifically about the number of gray buttons not matching. So technically in this part of the instructions a user could have a fork or not am I interpreting correctly? Maybe the case is rare where someone with write permissions would need this level of detail and so it's better to write it for users with forks, so I could go either way on it really.

**Comment by georgemccabe** [comment]
Yes, I agree that the instructions could be made more clear regarding the differences between using a fork and using the dtcenter repo.

**Comment by georgemccabe** [comment]
@DanielAdriaansen 

> This section was confusing. I copied my env bash file to mohawk as myself to my own area. When I runas met_test, I couldn't source the file in my own area, and met_test does not appear to have write privileges in /d2/projects/METplus/METplus_Data_Staging. Maybe this is by design but we can probably add a little to this section to make it clearer.

Which section is this referring to? I see [this step](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#copy-files-to-dtc-web-server) has you copy the files to mohawk into the staging dir, then later you source the env file from the staging dir as the mest_test user. I am able to source the env files as met_test from the staging dir and I confirmed the met_test user has write permissions in the staging dir. Perhaps you were trying to source from your personal directory which doesn't allow permissions for the met_test user? Or perhaps the instructions have been cleaned up since you wrote this?

**Comment by DanielAdriaansen** [comment]
> @DanielAdriaansen
> 
> > This section was confusing. I copied my env bash file to mohawk as myself to my own area. When I runas met_test, I couldn't source the file in my own area, and met_test does not appear to have write privileges in /d2/projects/METplus/METplus_Data_Staging. Maybe this is by design but we can probably add a little to this section to make it clearer.
> 
> Which section is this referring to? I see [this step](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#copy-files-to-dtc-web-server) has you copy the files to mohawk into the staging dir, then later you source the env file from the staging dir as the mest_test user. I am able to source the env files as met_test from the staging dir and I confirmed the met_test user has write permissions in the staging dir. Perhaps you were trying to source from your personal directory which doesn't allow permissions for the met_test user? Or perhaps the instructions have been cleaned up since you wrote this?

I can't recall any longer what exactly happened here (and my notes I pasted in aren't very helpful). Re-reading the guide again, I think I completed section 8.5.1-8.5.1.10 on seneca. Then, maybe I ignored the SCP copy/paste command which correctly puts the tarball and env file in the metplus_staging area. Ultimately, after reviewing the guide as-is in develop today, I don't feel there's a problem, or at least one I can recall.
