### ISSUE TITLE
Enhancement: Improve PBL use case to generate reproducible results

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2246]
The pbl/PointStat_fcstHRRR_obsAMDAR_PBLH_PyEmbed use case occasionally produces differences in the automated test output. The use case is set to be skipped in the automated use case difference tests.

## Describe the Enhancement ##
Investigate and fix the cause of the differences so that each run of the use case produces consistent results. Once this has been completed, remove the use case from being skipped in the automated diff tests.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
@georgemccabe I spent a little time setting up a testing environment. I ran the use case 11 times on seneca yesterday and today. The first 8 times yesterday occurred within 1 hour, while the last 3 times include an additional run yesterday and 2 from today spanning about 3 hours. I diffed the latest `.stat` file with the other 10 tests and there are no differences. I am open to suggestions or spending more time writing automated code to run the use case N times and then more code to post-process all the `.stat` files, but curious if you had any other suggestions first.

**Comment by georgemccabe** [comment]
I don't have any good suggestions. These sporadic differences are difficult to debug since it is hard to reproduce.

**Comment by jprestop** [comment]
Please note that this MET issue: [Bugfix: Resolve missing derived HPBL obs #2687](https://github.com/dtcenter/MET/issues/2687) will be worked on and these diffs are likely the cause of these use case diffs.

**Comment by DanielAdriaansen** [comment]
I read the description over on dtcenter/MET#2687, but I don't understand how it relates to this use case. This use case derives PBL inside Python, and does not use the FORTRAN subroutine mentioned in the other issue. Am I missing something?

**Comment by georgemccabe** [comment]
@DanielAdriaansen, I think you are correct that the MET issue is not related to these differences. I saw that there were differences related to PBL in MET and suggested that it may be related to this issue without looking into the details.

**Comment by DanielAdriaansen** [comment]
OK no big deal, thanks @georgemccabe just wanted to see how plugged in I needed to be on dtcenter/MET#2687.

**Comment by georgemccabe** [comment]
Maybe be fixed from dtcenter/MET#2897. Recommend adding this use case back to the automated tests and test that it can now generates reproducible results.

**Comment by georgemccabe** [comment]
We suspect that the results should be consistent now for the PBL use case, so I turned on the difference tests for it with 8358b6b. Closing this issue, but we should reopen it if we encounter differences with this use case again. Thanks @DanielAdriaansen and @JohnHalleyGotway for tracking down this bug!

**Comment by DanielAdriaansen** [comment]
@jason-english we feel that the reproducibility of the output from this use case was affected by a bug in MET when using Python embedding for point observations, and not due to any issue with the Python script being used. There was a synchronization problem with different elements of the observation metadata (namely `valid_time`), and the ordering of the input data (which can vary when using `glob` in Python) exposed this.

**Comment by jason-english** [comment]
Good to hear; thanks for letting me know !
