### ISSUE TITLE
Update documentation to reflect new METplus Wrappers name

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#225]

**Comment by JohnHalleyGotway** [comment]
This issue should be fixed in the first set of bugfixes but is not sufficient to create a new bugfix by itself.  Be sure to re-render the PDF!

**Comment by georgemccabe** [comment]
We decided to exclude the documentation updates from the bugfix release. These changes should go into develop and will be found in the next major release (3.0)

**Comment by DanielAdriaansen** [comment]
This issue is deprecated with the transition to Sphinx. The original issue stemmed from calling "METplus" "METplus Wrappers" inadvertently. METplus and METplus wrappers are two different things.
