### ISSUE TITLE
Capture Warning and Error Output in Logs

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#229]
Currently if a warning or error occurs in METplus, the message is output to the screen and not captured in the log message. Errors from the produtil config are now prevented by wrapping those functions with error checking and clean error reporting that is sent to the log file. We should ensure that other potential errors in the code are also captured.

I know the python logging utility has a option to set it to capture warnings to the log automatically. @jimfrimel does this functionality exist in the produtil logger? Also, is there a way to capture stderr messages and also put them in the logs?

We should be capturing any errors that may occur with a try/catch block and append the error message to the log file so that the user can refer to the log file to see what went wrong.

**Comment by jimfrimel** [comment]
See #113 
Lets Setup a repeatable scenario to re-produce this behavior. 
Yes we should be able to currently capture as long as logging is 'setup' Before the error occurs.

Is above referring to capturing the stderr of the external executables ?

**Comment by georgemccabe** [comment]
@jimfrimel  I was referring to errors that come from METplus. I believe all of the errors in the MET executables are captured in their logs.

**Comment by jimfrimel** [comment]
Ok I see this is referring to uncaptured exceptions in the scripts...right ?

**Comment by georgemccabe** [comment]
Yes, for example previously when you attempt to get a config item that isn't set. This no longer happens since we check first, but there are likely other situations where errors can occur in METplus.

**Comment by georgemccabe** [comment]
Errors and warnings are now caught in the METplus logs.
