### ISSUE TITLE
Documentation:Contributor's Guide Add instruction for pushing feature to upstream repository

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#2296]
## Describe the Task ##

In the Contributor's Guide, section [6.4.1.8](https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#push-the-feature-branch-to-github) add instructions for pushing the feature branch to the upstream branch (for users who have forked from the dtcenter/METplus repository) before requesting a Pull Request:

cd into the directory $YOUR_METPLUS_SOURCE/METplus
verify that the feature branch is correct:  _git branch_ 
verify that the upstream remote is set (see section 6.4.1.4): _git remote -v_ 
if not, follow the instructions under section 6.4.1.4

in section 6.4.1.8, after the git push origin <feature_777_wrapper_xyz> instructions,
include this:

Push changes to the upstream remote:
git push upstream <feature_777_wrapper_xyz>

with instructions inside a code box.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately  less than 1  day of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
I'm confused by this. If a user is working from a fork, then origin = {user}/{repo} and upstream = dtcenter/{repo}. They wouldn't have permission to push changes to the upstream if they need to create a fork, so `git push upstream <feature_777_wrapper_xyz>` would fail.

**Comment by jprestop** [comment]
@georgemccabe

> I'm confused by this. If a user is working from a fork, then origin = {user}/{repo} and upstream = dtcenter/{repo}. They wouldn't have permission to push changes to the upstream if they need to create a fork, so git push upstream <feature_777_wrapper_xyz> would fail.

I don't have much experience with forks, but looking through my notes when I forked from the hpc-stack repo, I do believe you are correct that the user would not have permission to push changes to the upstream.

**Comment by bikegeek** [comment]
not needed
