### ISSUE TITLE
Documentation: Update the Release Guide to document the release dependencies and completion indicator

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#2339]
## Describe the Task ##
From the [METplus 5.1.0 Coordinated Release Retrospective](https://docs.google.com/document/d/1_cfRYFYuYqazet793OSojZ-MPE5-CwEq0h-E-jIdnbM/edit), we discussed the need to assign release timeline appropriately and perhaps stagger dates for release cycles and the need to communicate with the team appropriately when releases are completed.

It was decided that we need to update the release guide for **official releases** of METplus and METviewer to state the dependencies (for METplus - all other components, except METexpress; for METviewer - METdataio, METcalcpy, METplotpy) of each and to indicate that an official release of these components should not be done until the dependencies have been released.

It was decided that the person cutting the METplus official release should send an email indicating the completion of the coordinated METplus release to the metplus-all(?) google group so that the Project Manager can then create the announcement to send out to the METplus community.

From John HG in Slack: FYI, I’d recommend creating a new top-level section, like after the Release Support Policy but before the Instructions Summary.

### Time Estimate ###
<1 day of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
RC1 release

### Funding Source ###
2782544 (NOAA Base)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Upon further review, this task has not been completed yet.  There already exists an Announce Release section, which needs to be updated based on the notes in the description and the release dependencies still need to be documented.

**Comment by JohnHalleyGotway** [comment]
Recommend also modifying the instructions slightly for RC1 releases.

Currently, we create the main_vX.Y branch [when creating the official release](https://metplus.readthedocs.io/en/develop/Release_Guide/met_official.html#create-release-branch). Recommend moving this step from the official release to the RC1 release.

RC1 means that we think the code is good to go from a developer perspective. So creating main_vX.Y at that time is defensible. And that makes the develop branch available to accept enhancement slated for the next official release.

Once main_vX.Y exists, we'll need to fix bugs in both it and the develop branches. But between RC1 and the official release those branches should be almost identical, and fixing the same thing in 2 similar branches can likely be done with cherry-pick - which is a one-liner.
