### ISSUE TITLE
Create unit tests for series_by_init.py

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#235]
There currently aren't any unit tests for the series_by_init.py wrapper.  Creating these tests will be especially useful for the transition from Python2 to Python3.

**Comment by bikegeek** [comment]
Creating non-unit tests to verify that the expected number of files is created and that the expected filtered files are being created for now.

**Comment by bikegeek** [comment]
Don't forget to add to the run_pytests.sh script so that this test can be run with the other existing tests when this script is invoked.

**Comment by bikegeek** [comment]
added entry to run_pytests.sh script, using staged data on 'eyewall', under the /d1/METplus_test_input/extract_tiles directory as input.

**Comment by bikegeek** [comment]
Gihub Issue #331 and #332 need to be completed before addressing this issue

**Comment by georgemccabe** [comment]
This was completed with #310
