### ISSUE TITLE
Clean up GitHub wiki broken links and out-of-date information

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#237]
The link to the coding conventions in the GitHub wiki is no longer pointing to the NCEP coding conventions doc, or the coding standards that are employed by METplus.

**Comment by georgemccabe** [comment]
We should review this content and either remove the old content or update it. Most of our information now lives in the User's or Contributor's Guide, so most of this should be removed to avoid confusion.

**Comment by georgemccabe** [comment]
@jprestop has cleaned up the front page of the GitHub wiki with useful links and information. We still need to review/clean-up/remove the other wiki pages.

**Comment by georgemccabe** [comment]
I updated the links on the home page of the wiki. I removed wiki pages that are no longer relevant or already covered in the Contributor's Guide. I moved a few references to the Contributor's Guide since that seems to be a more appropriate location for that information.
