### ISSUE TITLE
METplus User's Documentation corrections

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#238]
Rob from UKMO has found some typos and made some suggestions for the METplus User's Documentation and README files that are downloaded with the source.  Here are the issues captured from Wednesday June 5, 2019:

The following are questions posed by Rob after following the METplus User’s Documentation:

METplus docs typos, questions:

**2.5  directions for cloning should precede the description of the directories**

**(swap 2.5 and 2.6)???**

2) should we add env instructions for ksh in addition to bash and csh???

3)  Wrappers configurations file  need to update the README in the code to account for the
addition of the logging config file 

**4) chapter 2 sample data instructions need to be updated to reflect the actual names and
the individual tar balls that comprise the sample data**

**5)  2.9  running METplus wrappers remove the text about adding to the [config] header 
because we are creating an empty file and this doesn’t exist.   Explicitly recommend copy 
and paste the following text below…**

6)  put a note/warning that on some systems, may need to replace the // with # for 
comments in the config file whenever you observe parsing error message that 
corresponds to the lines where the comments reside.

6b) Search all METplus .conf files in the repo and replace '//' comments with '#' and fix docs in METplus User's Guide 2.1 section 2.9.

**7) page 23 before section 2.9 “...with <path/to> with …” should be reworded…**

8) bottom of page 21 in e.g. box for csh instructions for set path, missing }???

9) In METplus/parm/README file references either 2 or 3 directories... but that count is not accurate.  When possible, remove specific number to avoid having to keep them accurate.

**10) We need to clarify that in order to run the Cyclone example use case, you first need to download that input data.  We need to remind users that they need to sample data needed for each use case.**

11) Rob Darvell alerted use that he also gets mpi warnings from the produtil code.  Would be great in the refactor of produtil (2 to 3) to get rid of these warnings!

**12) Point Stat section number far off to the right (pg 37)- wrong space char??**

**13) Section 3.14 VAR_LIS and STAT_LIS don’t have section numbers associated with them**

**14) 3.18.2 remove text following the Configuration header**

15) Master_metplus.py still has ToDo’s that should be removed and become GitHub issues

16) Remove the point stat documentation odt and pdf from the repository

**17) Chapter 4 VALID_INCREMENT change wording from “at 6 hour increments” to “in 6 hour increments” and search for this text pattern throughout and make any necessary replacements**

**_18) pg 52 provide more explanation of the example, replace “forecast least list” with “forecast lead list”_**

19) pg 57 Chapter 4  Refer to MET user’s manual chapter x for a description of the grib_level, and other “extras” 

20) pg 60 provide more explanation for the fifth file in the example

_**21) Chapter 4 page 61 sample tarball files names need to be updated**_

**22) Promote 4.6 to any section before the A-Z glossary**

23)Change the A-Z glossary to Appendix

**Comment by DanielAdriaansen** [comment]
@bikegeek @JohnHalleyGotway is this list a list of "must-do's", or are these open for discussion among the team? For example, number 23 can easily be accomplished but I don't want to just blindly make all these changes. How do we go about agreeing which to do and which not to do?

**Comment by JohnHalleyGotway** [comment]
We met with Rob during his visit and reviewed his feedback about the documentation when writing up this issue.  I'd proceed with doing all of them unless you come across a good reason not to.

For example, #2 may be a bad idea since it's seldom a good idea to list duplicate info.  Maybe instead of listing all conventions, just specify the one we're using and alert users that they may need to modify based on their shell.  That being said, bash commands are probably the most widely used.  And I *think* bash and ksh commands are identical.

**Comment by georgemccabe** [comment]
I also thought that bash and ksh syntax was identical, at least for the
commands we have in the guide. Maybe Rob was suggesting to put 'bash or
ksh' above those commands so that people using ksh are clear which to use
if they don't know that it is similar to bash.

**Comment by DanielAdriaansen** [comment]
OK thanks for the feedback everyone. I have made a first pass through these and any item that is in **BOLD** is complete (pushed to develop). Items in **_BOLD/ITALIC_** are partially complete. Other items are probably better suited for a developer to complete. Please find my summary/questions of each remaining/partial issue below:

Item 2. Developer should complete
Item 3. It is not clear what he means to me
Items 6/6b. Developer should complete
Item 8. Developer should complete to ensure correct bracket is used
Item 9. This file needs to be completely updated- should we create a new github issue?
Item 11. Developer should address
Item 15. Developer should complete
Item 16. Does he mean the two files parm/use_cases/grid_to_obs/README_grid_to_obs.pdf and parm/use_cases/grid_to_obs/README_grid_to_obs.odt? I was unsure.
Item 18. Can a developer provide more information on this example based on how it works?
Item 19. Developer should complete
Item 20. Author of example/developer should expand
Item 21. I think this is the same as number 10 in his list, which I fixed but can someone confirm?
Item 23. Lyx expert should complete. I attempted changing the AZ-glossary to an appendix and completely ruined my Lyx files and had to start over. Maybe @JohnHalleyGotway or someone on MET knows how to quickly change a section/sub-section to appendix?

Tagging Minna/Jim/George for developer related items
@bikegeek @jimfrimel @georgemccabe

**Comment by j-opatz** [comment]
Confirmed that updates were completed with newer METplus releases, remaining issues not covered were completed in addition to list in #442.
