### ISSUE TITLE
Update logic for setting the plot_data_plane title.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#24]
The series_by_lead.py code calls get_nseries() to determine the number of points over which the stats were computed.  However, if "TOTAL" wasn't requested for series-analysis, then we get an error.  Update the logic for get_nseries() to check for series_cnt_TOTAL... if missing, return a bad data value rather than erroring out and then omit the "(N = TOTAL)" from the plot_data_plane title string.

Also, the title for plot_data_plane has a hard-coded reference to GFS.  Instead, lookup the MODEL variable from constants.pdef

Related GitHub Issue #23

**Comment by georgemccabe** [comment]
This should be covered when tackling #671
