### ISSUE TITLE
Comparison wrappers like GridStat have not been tested using NetCDF probabilistic forecast data

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#244]
We have only tested on grib2 data. The format of the field info is different for NetCDF data, so we need to test that it builds the items correctly.
NetCDF uses prob=TRUE;

**Comment by georgemccabe** [comment]
This involves finding a use case that uses probabilistic forecast data (FCST_IS_PROB = TRUE) and run the input data through a tool like RegridDataPlane (could use the same file as the verification grid) to generate a NetCDF file, then see if that file can be used as input to GridStat.

There is a chance that it will not work and the command will have to be called using prob= { name=... instead of just prob=TRUE;. If that is the case, you may need to add a config variable to determine if the prob item should be defined as a dictionary or a boolean.

**Comment by CPKalb** [comment]
I should have probabilistic netCDF data that we can test this on, but I need to find it.  Is there a specific place I should put this netCDF data once I find it, or should I test it wherever it's located?

**Comment by georgemccabe** [comment]
You can test it where it is located, but we may want to include it in the met_test sample data so we have an example of this new input being used.

Any update on this work? If it does not work we will need to make code changes, so we need to get that in before the code freeze.

**Comment by CPKalb** [comment]
It doesn't work yet.  The error I'm getting in my log file is this:

ERROR  :
ERROR  : GridStatConfInfo::process_config() -> The number of verification tasks in "obs.field" (1) must be non-zero and match the number in "fcst.field" (9).
ERROR  :

Any idea what this means?

**Comment by CPKalb** [comment]
I see another issue in the log file.  When using probabilities with netcdf files, the variable name should not be "PROB"

**Comment by CPKalb** [comment]
I had to remove the quotes around the ${CLIMO_FILE} in the met GridStat configuration file to get this to run.  But once I did that, it ran.  However, I get 36 output lines instead of the 4 that I get when running this directly in MET, so something is still not working as it should be.

**Comment by georgemccabe** [comment]
Added config variables [FCST/OBS]_PROB_IN_GRIB_PDS that need to be set to determine how to format probabilistic field info if INPUT_DATATYPE is not set to NETCDF. The new variables can either be set to FALSE or INPUT_DATATYPE to NETCDF to handle NetCDF probabilistic input correctly.

**Comment by georgemccabe** [comment]
Moved Tina's config files for this test into internal_tests/config so that it can be preserved and be used for future testing.

**Comment by georgemccabe** [comment]
Input data used for test is on eyewall under /d1/METplus_Data/prob_nc_testing in case we want to make this a use case in the repo and provide the input data.
