### ISSUE TITLE
Update Documentation Overview and Conventions

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplus#2454]
*Replace italics below with details for this issue.*

## Update Sphinx online editor ##
When trying new editing tools, it can be handy to have a quick place to see if the changes actually work or not in Sphinx.  Without this editor it can take up to 5 minutes to see if the changes worked while it builds in ReadTheDocs.  Having an online editor makes things run more smoothly.

The OLD editor was [livesphinx](https://github.com/faust93/livesphinx) and is no longer working or supported.  (There was another version before this one that is also out of service.)

The NEW editor is https://www.tutorialspoint.com/online_restructure_editor.php and needs to be updated in section 10.2.19.1. [Testing RST Formatting in an Online Editor](https://metplus.readthedocs.io/en/develop/Contributors_Guide/documentation.html#testing-rst-formatting-in-an-online-editor).

## Update tables information ##
1.  It is possible to use csv files to automatically create tables.  Add something like [this information](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#csv-files) to our tables section.

2.  Also note this example of a grid table under 3.4.3. External Library Handling in compile_MET_all.sh of the MET installation guide, IF THE USER ALREADY HAS THE LIBRARY DEPENDENCIES INSTALLED table.  John HG had to do some fancy maneuvering to get this to line up correctly.  Please note that that one way to force table to use line break inside a cell is inserting an empty line between them.  This works in a gridded table.    Please note, this is currently in a feature branch, not develop: https://met.readthedocs.io/en/feature_2588_install_rewrite/Users_Guide/installation.html#external-library-handling-in-compile-met-all-sh

3.  If it's a list table, to create a line break use :raw-html:`<br />` see [Table 13.8 Format information for SSVAR](https://met.readthedocs.io/en/latest/Users_Guide/ensemble-stat.html#id8) line 37-38 as an example. Here is the [raw sphinx](https://raw.githubusercontent.com/dtcenter/MET/feature_2588_install_rewrite/docs/Users_Guide/ensemble-stat.rst). 

## Update code within a paragraph ##
Add this information to the [code blocks section](https://metplus.readthedocs.io/en/develop/Contributors_Guide/documentation.html#code-blocks)

To add coding information within a paragraph:
:code:`information to highlight`

## Adding a section for Duplicate Links ##
This will address the "WARNING: Duplicate explicit target name".  Add this under Troubleshooting.

### Time Estimate ###
*Estimate the amount of work required here.*
*1 to 3 days*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###

2702691, 2784543 and 2799991 equally
### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.  This is not a change that will effect other modules
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@lisagoodrich When you are finished working on #2463, this issue could be a good one to work on next.

**Comment by georgemccabe** [comment]
@lisagoodrich , @jprestop , just confirming that I can close this issue.
