### ISSUE TITLE
The Point-Stat config files in METplus were not fully updated for met-8.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#248]
This is based on a met-help issue from Perry Shafran:
   https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=90740

When he runs Point-Stat via METplus he gets:
ERROR  : PointStatVxOpt::set_vx_pd() -> "message_type_group_map" must contain an entry for "LANDSF".

I see that the Point-Stat config files included in METplus were not fully updated for met-8.1.  Specifically, we need to update the message_type_group map setting by adding entries for LANDSF and WATERSF:

Here's the default setting for met-8.1:
message_type_group_map = [
   { key = "SURFACE"; val = "ADPSFC,SFCSHP,MSONET";               },
   { key = "ANYAIR";  val = "AIRCAR,AIRCFT";                      },
   { key = "ANYSFC";  val = "ADPSFC,SFCSHP,ADPUPA,PROFLR,MSONET"; },
   { key = "ONLYSF";  val = "ADPSFC,SFCSHP";                      },
   { key = "LANDSF";  val = "ADPSFC,MSONET";                      },
   { key = "WATERSF"; val = "SFCSHP";                             }
];

**Comment by georgemccabe** [comment]
I added the land and water message items to the PointStat config files under grid_to_obs and pushed the changes to master_v2.1. Do we want to cut another bugfix release for this change?
