### ISSUE TITLE
Remove the `TC_RMW_MAX_RANGE_KM` configuration option 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2513]
## Describe the Task ##
The dtcenter/MET#2833 bugfix proposes 2 changes that may impact the METplus wrappers repo:
1. Removing the `max_range_km` configuration option from the TC-RMW configuration file means that the corresponding METplus [TC_RMW_MAX_RANGE_KM](https://metplus.readthedocs.io/en/latest/Users_Guide/glossary.html#term-TC_RMW_MAX_RANGE_KM) configuration option should also be removed. Note that this includes removing it from the wrapped [TC-RMW MET config file](https://github.com/dtcenter/METplus/blob/1c98712320771cc2df84d9557a8046f4d17aad75/parm/met_config/TCRMWConfig_wrapped#L80).
2. Changing the default setting for `rmw_scale` from 0.2 to NA means that, by default, the range/azimuth grid will be defined by the `delta_range_km` config option rather than the `rmw_scale` option. Setting `rmw_scale` to a non-NA value takes precedence over the `delta_range_km` option and overrides this default behavior.

Note that off-by-one bugs exist in defining both the range and azimuth values for both TC-RMW and TC-Diag. Fixing these bugs will lead to changes in the METplus output for any calls to TC-RMW or TC-Diag.

PR dtcenter/MET#2840 for issue dtcenter/MET#2833 was merged into develop on 3/27/24 during the beta4 development cycle. This METplus issue can be fixed during either the beta4 or beta5 development cycles. Please re-schedule as needed.

You only need to make this change for the develop branch. In my opinion, no change is needed in a METplus-5.1 bugfix release since having an extra unused configuration option does not cause any harm.

### Time Estimate ###
2 hours?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No other impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This work was completed as part of PR #2606. When that PR is merged, this issue can be closed.
