### ISSUE TITLE
metplus_system.conf still has deprecated names in non-MET executables section

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#252]
The following need to have the _EXE removed from their names:

RM_EXE = /path/to
CUT_EXE = /path/to
TR_EXE = /path/to
NCAP2_EXE = /path/to
CONVERT_EXE = /path/to
NCDUMP_EXE = /path/to
EGREP_EXE = /path/to

so this will conform with the latest updates

**Comment by georgemccabe** [comment]
This has already been changed in the develop branch and will be included in the 3.0 release
```

[exe]
# NON-MET executables
# if the executable is in the user's path, METplus will find it from
#  the name. If the executable is not in the path, specify the full
#  path to the executable here (i.e. RM = /bin/rm)
WGRIB2 = wgrib2
RM = rm
CUT = cut
TR = tr
NCAP2 = ncap2
CONVERT = convert
NCDUMP = ncdump
EGREP = egrep

```
