### ISSUE TITLE
Documentation: Add the METplus development timeline for the next official release to the User's Guide

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2530]
## Describe the Task ##
This suggestion arose during the NOAA METplus Telecon on April 1, 2024. The development timeline for the next official coordinated release is specified in the settings of the corresponding GitHub project. For example, in the [METplus-Wrappers-6.0.0 Development](https://github.com/orgs/dtcenter/projects/76) project, the [cycle setting](https://github.com/orgs/dtcenter/projects/76/settings/fields/35871112) defines the target dates for future releases. While the project iteself is public, the settings (including the cycles) are only visible to those with write access, namely those on the METplus Team in the DTCenter GitHub org.

This issue is a documentation task to update the [METplus Release Information](https://metplus.readthedocs.io/en/develop/Users_Guide/release-notes.html) chapter to list out the planned development timeline.

Recommend only putting this in one spot though because anytime we change our schedule, we'll need to update it...
1. In this METplus documentation.
2. In the cycle settings of the METplus, MET, and METplus-Analysis project boards.

Also update the Release Guide for METplus Wrappers to handle this update.

Recommend the following...

Development toward the METplus 6.0.0 Coordinated Release is ongoing and is broken down into the following development release cycles for each component:
1. **Beta1** releases for the METplus components occurred around 2023-09-15.
2. **Beta2** releases for the METplus components occurred around 2023-11-14.
3. **Beta3** releases for the METplus components occurred around 2024-02-08.
4. **Beta4** is tentatively scheduled for 2024-04-10. 
5. **Beta5** is tentatively scheduled for 2024-06-05.
6. **Release Candidate 1** has not yet been scheduled.
7. **Official Release** has not yet been scheduled.

Update the development release instructions... and remove this content when creating the official release.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None needed.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@JohnHalleyGotway, can this issue be closed?
