### ISSUE TITLE
README Files - create consistent template for use cases

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#254]
Add README files for each use case directory.
Suggest the following layout:
parm/use_cases/README contains a description of settings common to multiple use cases.
parm/use_cases/*/README contains a description of settings specific to that use case.
The README's will automatically be included into the METplus user's guide in Sphinx.  So we need a template for them to ensure consistency.  And perhaps they'll need to be in .rst format?
This change was requested by the UKMO to increase ease of use.

**Comment by DanielAdriaansen** [comment]
#238 also has references to README corrections that may be able to be resolved with this issue.

**Comment by JohnHalleyGotway** [comment]
Discussed this during the METplus meeting on 7/15/2019.  We redefined this task by splitting out the "updating" portion into #262.  Moved this issue from METplus-2.2 to METplus-3.0 since we should coordinate it with development of the user's guide.

**Comment by DanielAdriaansen** [comment]
A template for documenting use cases can be found in the METplus repository [here](https://github.com/NCAR/METplus/blob/master_v3.0/parm/use_cases/template/use-case-application.py).
