### ISSUE TITLE
Create new use case for DAI APIK project (S2S domain - precip products)

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METplus#260]
This use case will evaluate the skill of forecasts of rainfall in the Subseasonal-to-Seasonal (S2S) domain for several different metrics: 
- relative frequency (e.g., probability of exceeding 100 mm in a month), 
- precipitation intensity (# of days with precip greater than a threshold), 
- etc.  

This use case is being developed for the DAI APIK project (Indonesia). 

The goal of the outcome of this use case is to assess whether BMKG's S2S forecasts are skillful in allowing agricultural decision makers to make better decisions. 

Eventually, this use case may include a conditional analysis, which uses the seasonal cycle/ENSO/IOD/MJO to condition the skill according to these different regimes. 

Initially, this use case will be set up to use 25 years of CFSv2 S2S forecast data (maybe eventually, it will use ECMWF System V S2S forecast data or BMKG's downscaled S2S forecast data). 

For observations, we will start by using use gridded satellite observational analysis (e.g., CHIRPS - Funk et al.). Eventually, we may use BMKG's gauge data.

Output goals:
- Reliability diagram
- Scorecard (could do for each main region)

**Comment by jvigh** [comment]
Caspar has proposed a streamlined example use case to use for the METplus training for the Philippines and Indonesia. Caspar would like this development to be complete in time for the Philippines training, which will be in early August.  

This use case compares NMME seasonal forecast data (monthly, 29 years, 1982 - 2011?) to monthly precipitation analyses from CPC. Details are provided below.


**NMME Data**

Root: /glade/work/ammann/NMME
Resolution: 1x1-degrees

**Observations   $root/obs**

*Precipitation*
 - obs_cpc_pp.1x1.nc (precip)
 - obs_cmap.1x1.nc (precip)

*Temperatures*
 - obs_ghcn_cams.1x1.nc (tmp2m) -- land
 - obs_oisst.1x1.nc (tmpsfc) -- ocean

**Forecasts  $root/forecast/monthly**
- NMME.prate.201907.ENSMEAN.anom.nc  (fcst(target,lat,lon))
with target = 714-725: Jul2019-Jun2020)
- NMME.tmp2m.201907.ENSMEAN.anom.nc (fcst(target,lat,lon)
with target = 714-725: Jul2019-Jun2020)

**Hindcast  $root/hindcast/monthly**
- nmme_pr_hcst_JulIC_8_1982-2010.nc (pr(time,lat,lon), time = Aug1982-Aug2010)
- nmme_pr_hcst_JulIC_9_1982-2010.nc (pr(time,lat,lon), time = Sep1982-Sep2010)
.
.
.
- nmme_tas_hcst_JulIC_8_1982-2010.nc (tas(time,lat,lon), time = Aug1982-Aug2010)
- nmme_tas_hcst_JulIC_9_1982-2010.nc (tas(time,lat,lon), time = Sep1982-Sep2010)
.
.
.


**NMME Exercises: using July 1 Initial Conditions**

1) Anomaly characterization -- monthly mean fields: August 2019 forecast vs August Climatology
- Anomaly: field
- Determine regions with high rainfall, temperatures anomalies
- Alternative: compare two observational datasets: precipitation

2) Mean forecast error with July Initial Conditions: August forecasts errors 
- Mean field error to determine bias: 29x anomaly - metrics 
-- bias
-- anomaly correlations
-- ranked probability skill score
-- MODE - use threshold-based evaluation
- Do bias correction on forecast using hindcast error / bias
- Mask forecast with regions of skill
- Mask skill sign of anomaly 

Ensemble forecast: 
Probability of ?

**Comment by TaraJensen** [comment]
George, Please support Jonathan on developing this qpf use case.  He has a 2 week turn-around on it.  Account key 776113 APIK

**Comment by georgemccabe** [comment]
@jvigh , can this issue be resolved?

**Comment by georgemccabe** [comment]
This work has been completed, but we still need to clean up a use case configuration to add to the repository because this use case utilizes new functionality that hasn't been covered in a use case prior to this work. We also need to obtain some sample data to add to a sample data tarball for the next release.

**Comment by georgemccabe** [comment]
Input data and config files are now available on kiowa under /d1/projects/APIK. Documentation file is found under parm/use_cases/model_applications/s2s. Need to:

- put config files in use case dir
- put input data in sample data location
- fill out rest of information in doc file

**Comment by georgemccabe** [comment]
Config files are now found in s2s directory (seasonal_forecast.conf METplus config and GridStatConfig_APIK_S2S_use_case_1 MET config file)

Sample input data is available on eyewall in /d1/METplus_Data/model_applications/s2s

Still need to clean up doc file and config files, but they now run in the correct structure.

**Comment by georgemccabe** [comment]
This use case has been added to the repository for the 3.0 release.  Adding issue #384 for adding SeriesAnalysis portion via METplus.
