### ISSUE TITLE
New Use Case: Multivariate MODE for RRFS

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#2647]
## Describe the New Use Case ##
As provided by Sarah Griffin (UW-Madison):

This use case demonstrates how to run Multivariate MODE to identify complex objects from two or more fields defined by a logical expression. In this case, MODE super-object intensity statistics were output for both radar reflectivity and lightning. Using the MODE_MULTIVAR_INTENSITY_FLAG, the user can control for which variables super object intensity statistics will be output.

### Use Case Name and Category ###
*Provide use case name, following Contributor's Guide naming template, and list which category the use case will reside in.*
*If a new category is needed for this use case, provide its name and brief justification*
Use case name will be MODEMultivar_fcstRRFS_obsGOES_MRMS_BrightnessTemp_Lightning

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 
Forecast is RRFS
Observations are GOES BT, GLM data and MRMS radar reflectivity.
Total file size is 259 mb

### Acceptance Testing ###
*Describe tests required for new functionality.*
Needs to be tested locally for successful run, but has been confirmed to run on user's system

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
@sarahmonet Thanks for joining github, we should be able to accomplish all the necessary steps to finish your use case for inclusion in the METplus repository from here. For posterity, I'll be listing what steps I'm doing, along with any requests for you.

To begin, I've created a new feature branch that will house all of the files (except for the input data files) associated with the sue case. These files include

- Documentation for the use case
- The METplus wrapper configuration file
 
The creation of that branch follows the steps outlined in the [METplus Contributor's Guide](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html#workflow-overview). Following the guide, the branch's name is feature_2647_useCase_MvMODE_for_RRFS. Here's [a link to the github page detailing the branch](https://github.com/dtcenter/METplus/tree/feature_2647_useCase_MvMODE_for_RRFS). There's currently only one file changed from the develop branch (the documentation file), but more will be added as time goes on. For now, this establishes the working branch.

My next step will be to fill out the documentation file with the information you provided.

What I need from you is the configuration file to run the use case, as well as the necessary input files. In order to submit those, you'll need to follow the guidance in this Discussion to ftp the data to us. 

**Please note, any data you send via this method will be automatically removed after 7 days. So it's important that once you've completed this task, you add a comment to this issue stating the data is available (as well as the name of the directory you created).**

Once you've let me know the files are up on the ftp server, I'll collect them and discuss the next steps.

**Comment by sarahmonet** [comment]
I have looked through this thread, but I cannot find any information about which ftp site I should send this data to. I'm sorry if I missed something.

**Comment by jprestop** [comment]
Hi @sarahmonet.  I work with John and thought I'd follow up with the ftp information. On the front page of our Discussions, there is a post at the top with a title "[How to Send Us Data](https://github.com/dtcenter/METplus/discussions/954)", which I've linked here for your convenience.  I hope that helps.

**Comment by sarahmonet** [comment]
Thank you! I have now added the data for the use case to the ftp site.

**Comment by jprestop** [comment]
Thanks @sarahmonet.  
@j-opatz I put the files on seneca at /d1/projects/METplus/discussions/2647.

**Comment by j-opatz** [comment]
Thank you providing the data, @sarahmonet (and thank you @jprestop for pulling the data off the ftp site).

As of today, the documentation for the use case is basically complete in the feature branch (I still need to update the thumbnail image and output directory structure, along with some minor cosmetic touch-ups). The next step is to test the use case for a successful run on our systems. 

If there are any issues, I will reach out and with your guidance I hope to solve those issues.

When the use case runs without any issues, then I will update the configuration file to a more generic state: that means less hard-coded directories and more environment settings so other users can easily run your use case when it's added to the METplus repository. I'll reach out when that task is complete to show you the results, as well as the next steps of updating the internal METplus automation files and getting the input data bundled up and ready for submission to our data server.

**Comment by j-opatz** [comment]
@sarahmonet, it looks like there are some runtime errors in the configuration file you provided. The lightning fields seem to be improperly set, resulting in the following error:

```
ERROR  : 
ERROR  : Mode_Field_Info::set() -> Field:LTNG_entireatmosphere.  When 'merge_flag' is explicitly set, 'merge_thresh' must be explicitly set for multivariate mode
ERROR  : 
```
This error occurs twice, once for each forecast lead. When I took a look inside the configuration file at the `LTNG_entireatmosphere` field, this is what I found:
```
FCST_VAR3_NAME = LTNG_entireatmosphere
FCST_VAR3_LEVELS = (*,*)
FCST_VAR3_OPTIONS = conv_radius = 3; conv_thresh = >SFP10; merge_flag = THRESH; file_type = NETCDF_MET; censor_thresh = [<= 0]; censor_val = [-9999]; vld_thresh = 0.5; inten_perc_value  = 100; inten_perc_thresh = NA
```
I see that `merge_flag` is set to THRESH, but as the error mentions, there's no accompanying `merge_thresh` setting. What value should this be set to?

**Comment by sarahmonet** [comment]
Interesting, I wonder how it was able to run for me just fine?? Here's what those lines should be. merge_thresh is the same as conv_thresh

FCST_VAR3_NAME = LTNG_entireatmosphere
FCST_VAR3_LEVELS = (*,*)
FCST_VAR3_OPTIONS = conv_radius = 3; conv_thresh = >SFP10; merge_thresh = >SFP10; merge_flag = THRESH; file_type = NETCDF_MET; censor_thresh = [<= 0]; censor_val = [-9999]; vld_thresh = 0.5; inten_perc_value  = 100; inten_perc_thresh = NA

OBS_VAR3_NAME = flash_extent_density
OBS_VAR3_LEVELS = (*,*)
OBS_VAR3_OPTIONS = conv_radius = 3; conv_thresh = >SOP10; merge_thresh = >SOP10; merge_flag = THRESH; file_type = NETCDF_MET; censor_thresh = [<= 0]; censor_val = [-9999]; vld_thresh = 0.5; inten_perc_value  = 100; inten_perc_thresh = NA

**Comment by j-opatz** [comment]
Hi @sarahmonet,

My apologies for such a long delay since your last message; there was a mix of travel time and internal misfortunes that set back the original time table on this use case. Thank you for your patience during the interim.

I was able to add in the `merge_thresh` settings you indicated and was met with success! The use case produces the output you indicated. However, there does seem to be an error related to improper use of a configuration setting.

I noticed in your configuration file you currently have 
```
FCST_IS_PROB = FALSE,FALSE,TRUE
```
I think this is to indicate that the last forecast field variable, `LTNG_entireatmosphere`, is probabilistic. However this is an improper setting for `FCST_IS_PROB`, which can only accept a single Boolean. 

As proof of this issue, there's an error (but not a fatal one) in the log file for the use case:
```
(config_metplus.py:753) ERROR: [config] FCST_IS_PROB must be an boolean.
```
When we look at the METplus code responsible for handling `FCST_IS_PROB`, we find the following:
```
   is_prob = config.getbool('config', name) if name else False
```
What this code indicates is that entering anything other than a TRUE will result in the setting being equal to FALSE. So as it stands, the  `LTNG_entireatmosphere` field is not being evaluated as probabilistic.

This can be corrected, though! Assuming that we want `LTNG_entireatmosphere` to be probabilistic, we can use the `FCST_VAR3_OPTIONS` setting to create `fcst_is_prob = TRUE;`.

Please let me know if this is the correct interpretation of your settings. If it is, I'll make the correction, rerun the use case to make sure it works as expected, then continue to move this toward a METplus repository use case.

**Comment by sarahmonet** [comment]
Hi @j-opatz,

I'm so sorry to hear about Tara (Jason O told me). She was a wonderful person.

To answer your question, I set  
FCST_IS_PROB = FALSE,FALSE,TRUE
because the thresholds for LTNG_entireatmosphere are set based on the data, so >=SFP75 sets the threshold based on the data. For example:
DEBUG 3: The requested percentile (99%) for threshold threshold ">=SFP99(31.34151)" includes 98.9999% of the data.
DEBUG 3: The requested percentile (99%) for threshold threshold ">=SOP99(29.48955)" includes 98.9999% of the data.
DEBUG 3: The requested percentile (99%) for threshold threshold ">=SFP99(31.34151)" includes 98.9999% of the data.
DEBUG 3: The requested percentile (99%) for threshold threshold ">=SOP99(29.48955)" includes 98.9999% of the data.

I thought that's what FCST_IS_PROB is referring to. Is that correct, though? I'm not sure after reading your comment.

**Comment by j-opatz** [comment]
Thank you for the condolences, @sarahmonet. It seems like everyone who knew her was able to experience the remarkable person she was. I'm glad to know you had that opportunity.

Thank you also for explaining the reasoning behind the `FCST_IS_PROB` usage. That setting tells METplus that the field should be analyzed as a probabilistic field; so it should find values ranging from 0 to 1 or 0 to 100 (a field ranging 0 to 100 is rescaled from 0 to 1 before processing). This allows access to the PCT, PSTD, and PJC line types, assuming the correct thresholding has been supplied. As mentioned above, it takes only a single Boolean and will default to FALSE if it finds anything else.

When utilizing thresholds such as SFP and SOP, METplus doesn't need to have a probabilistic data field: those sample percentiles are calculated from a sample of the data, regardless of its range. In fact the requested percentile is recalculated by METplus, which is something those DEBUG messages you copied show (the 98.9999s).

So if I'm understanding correctly, there may have been a mistaken belief that you needed to utilize `FCST_IS_PROB` to access the SFP,SOP thresholds. If that's the case, I can simply remove that setting and your use case should still run fine.

**Comment by sarahmonet** [comment]
Hi @j-opatz, yes there was a mistake on my end understanding the FCST_IS_PROB usage. It can be removed.

**Comment by j-opatz** [comment]
Great news,

Things are moving along quickly now that the configuration file is in order. I went through and changed all of the input paths to fit the standard:
```
{INPUT_BASE}/model_applications/category_name/use_case_name
```
which allows us to run automated testing via Github actions. I also updated the automated testing list (.github/parm/use_case_groups.json and internal/tests/use_cases/all_use_cases.txt) so Github knows how to run it.

I then created a local environment file (copyable from our servers via wget) that helped in taring the input files together. Both the environment file and tarball are now on our servers, where I'll set them up so they can be used in the automated testing (and eventually added to the short_range tarball for downloading for everyone). 

The next and final steps are to complete a PR, check that the automated testing succeeds (or find any bugs and fix them), and then your new use case will be part of the METplus repository!

**Comment by j-opatz** [comment]
@sarahmonet as you can see above, there's been a merge from the feature branch that I was working on into the develop branch. What this means is that when the develop branch is eventually used to create the METplus 6.0 coordinated release, all of the additions from the feature branch (i.e. everything to run your use case) will be in it!

As I mentioned in my previous entry, I also moved the tarball of the use case data up to our web server and merged it with the existing tarball for short range use cases using [the steps in the Contributor's Guide](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#adding-new-data-to-full-sample-data-tarfile). 

This use case was special in that it takes ~50 minutes to run, much longer than any of our current use cases. During its run time it overloads the disk space available to automated testing performed by Github (GHA), so it "fails". To get around this, I've disabled the need to have GHA run a test on the use case and noted [in the documentation of the exemption](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#use-cases-that-exceed-github-actions-disk-space). 

But that's it, the use case is now in the repository! Thank you again for your patience in all of this, as well as all of the work you completed to make this use case a viable one for future METplus users to work with.

**Comment by sarahmonet** [comment]
Thank you @j-opatz!!!
