### ISSUE TITLE
Add check for subtract mode for pcp_combine to see if lead time is equivalent to desired accumulation

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#271]
We need to have a check in the subtract mode so if the lead time is equivalent to the desired accumulation, we will run in -add mode with one input file to essentially just pass through the data and reformat it. 

**This comes from Ying Lin's met_help ticket 91205:**

PcpCombine in METplus for GFS forecasts: what to do about the first
accumulation period when T0 file has no APCP field:

In https://ftp.emc.ncep.noaa.gov/mmb/precip/METplus.question/gyre_run/

I want to get 24h GFS precip accumulation for forecast periods of
00-24h, 12-36h, 24-48h, with

FCST_PCP_COMBINE_METHOD = SUBTRACT

i.e. using the continuously-accumulating bucket (config
file:https://ftp.emc.ncep.noaa.gov/mmb/precip/METplus.question/gyre_run/gfs_24h.conf).
The computations for the 12-36h and 24-48h had gone well, but trying to
get the 00-24h accumulation using the same pcpCombine failed:

/global/noscrub/Julie.Prestopnik/met/8.1/bin/pcp_combine -subtract /gpfs/dell1/nco/ops/com/gfs/prod/gfs.20190719/12/gfs.t12z.pgrb2.0p25.f024 24 /gpfs/dell1/nco/ops/com/gfs/prod/gfs.20190719/12/gfs.t12z.pgrb2.0p25.f000 0 /meso/noscrub/Ying.Lin/metplus.out/gfs/bucket/fv3gfs.2019072012_f024_A24h -v 5

failed (No matching record found for 'APCP/A0' - https://ftp.emc.ncep.noaa.gov/mmb/precip/METplus.question/gyre_run/master_metplus.log.20190723).

It's understandable that trying to get 00-24h accumulation using
pcpCombine would fail since the zero hour model output does not contain
an APCP field.  The logical thing to do is just to extract the 00-24h
accumulation contained in the gfs.t12z.pgrb2.0p25.f024 file and convert
it to netCDF.  The question is, how to handle this within the framework
of METplus, e.g. how to tell METplus to run PcpCombine/SUBTRACT on all
accumulating periods except ones involving the initial hour, and for the
forecast hour that's equal to the length of accumulation, just convert
the amount to netCDF, so there'll be these netCDF files in
FCST_PCP_COMBINE_OUTPUT_DIR:

gfs.2019072012_f024_A24h (directly from gfs.t12z.pgrb2.0p25.f024)

gfs.2019072012_f036_A24h (from gfs.t00z.pgrb2.0p25.f036 and
/gfs.t00z.pgrb2.0p25.f012)

gfs.2019072012_f048_A24h (from gfs.t00z.pgrb2.0p25.f048 and
/gfs.t00z.pgrb2.0p25.f024)

**Comment by georgemccabe** [comment]
I discussed this with @JohnHalleyGotway and he mentioned that for precip accumulation (which is the majority of uses for this) we don't want to use 0 and this is a valid solution. However, some people use pcp_combine for other data, such as temperature differences. We should check the accumulation value and if it starts with A, we handle it this way. If not, we allow 0 hr values for subtract mode.

**Comment by georgemccabe** [comment]
This change has been added on feature_281_py_embed branch (related #211 and #281 ). I added a new use case conf in grid_to_grid called precip_continuous_zero_accum.conf to show this behavior. It has not yet tested that it still subtracts if the level difference is 0 and we are not processing accumulation

**Comment by georgemccabe** [comment]
Merged into develop branch.
