### ISSUE TITLE
Modify code to check for OBS_LEVEL=-1 and set to 0 as default for pcp_combine -sum mode

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#272]
We believe that setting OBS_LEVEL = 0 would solve this issue. However, the user shouldn't have to set this to 0. For "-add" mode, if OBS_LEVEL is not set, the code will try to figure out the accumulation to use. The code sets OBS_LEVEL to -1, if OBS_LEVEL is not set so we know to handle it this way. However, we use the same variable for "-sum" mode and -1 does not make sense here. We need to modify the code to check if it is -1 and set it to 0 as a default for "-sum" mode.

**This came from Ying Lin's met_help ticket #91205:**

pcp_combine -sum for verifying analysis:

In
https://ftp.emc.ncep.noaa.gov/mmb/precip/METplus.question/gyre_run/gfs_24h.conf,
there is

OBS_PCP_COMBINE_METHOD = SUM
    ...
OBS_PCP_COMBINE_INPUT_TEMPLATE = ccpa.{valid?fmt=%Y%m%d}/{valid?fmt=%H}/ccpa.t{valid?fmt=%H}z.06h.hrap.conus.gb2
OBS_PCP_COMBINE_OUTPUT_TEMPLATE = {valid?fmt=%Y%m%d}/ccpa.{valid?fmt=%Y%m%d%H}_A{level?fmt=%HH}h

(meant to sum up 6-hourly CCPAs to arrive at 24h CCPA)

This leads to the following err msg:

07/23 17:52:44.822 metplus.PcpCombine (command_runner.py:153) INFO: RUNNING: /global/noscrub/Julie.Prestopnik/met/8.1/bin/pcp_combine -sum 20190719_12 -1 20190720_12 24 /meso/noscrub/Ying.Lin/metplus.out/ccpa/bucket/20190720/ccpa.2019072012_A24h -pcpdir /com2/ccpa/prod/ccpa.20190720/12 -pcprx ccpa.t12z.06h.hrap.conus.gb2 -v 5 >> /meso/noscrub/Ying.Lin/metplus.out/logs/master_metplus.log.20190723 2>&1
ERROR  :
ERROR  : CommandLine::next_option() -> unrecognized command-line switch "-1"

(in
https://ftp.emc.ncep.noaa.gov/mmb/precip/METplus.question/gyre_run/master_metplus.log.20190723)

Is the setup for the OBS_QPE_COMBINE incorrect?  I don't know how the
'-1' flag got into the pcp_combine and how to get rid of it.

**Comment by georgemccabe** [comment]
This was actually for -sum mode, not -subtract mode.

**Comment by georgemccabe** [comment]
This change was made in feature_281_py_embed branch. It will be included in the changes for python embedding support. related #211

**Comment by georgemccabe** [comment]
Merged into develop branch.
