### ISSUE TITLE
Refactor tests for TcStat

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#274]
Now that the METplus release has sample data, use this same data in the test_tc_stat_wrapper.py script, rather than the data in the /d1/SBF/GFS directory on 'eyewall'.

**Comment by bikegeek** [comment]
The commands that are generated from calling the wrapper's run_all_times for the command line only tests are now causing MET error messages: 
ERROR  : 
ERROR  : AsciiHeader::read() -> trouble reading file:
ERROR  : /usr/local/met-8.0/share/met/table_files/met_header_columns_V8.1.txt
ERROR  : 

The wrapper is creating the command: 

/usr/local/met-8.0/bin/tc_stat -lookin /d1/minnawin/develop/series_by_init/tc_pairs/201412/mlq2014121400.gfso.0277.tcst -job filter -dump_row /d1/minnawin/develop/series_by_init

(also tried using met-8.1 with same error messages)

**Comment by JohnHalleyGotway** [comment]
Minna,

This error could happen if you ran MET version 8.1 code with the MET_BASE
environment variable set to reference the met-8.0 version.  So this is an
example of why we should avoid setting the MET_BASE environment variable
unless there's a good reason to do so.

John

**Comment by bikegeek** [comment]
And another reason to keep the test config files up to date whenever there are code changes....

Thanks,
M

**Comment by bikegeek** [comment]
updated the conf file and tests for the tc-stat via command line (ie job -filter ... etc provided by command line rather than in config file).  Work is being done on the branch: feature_274_fix_test_tc_stat , which was cloned from the METv2.2/develop branches on 7/25/2019 pm (after Hank made release and sync'd up the develop and METv2.2 branches).

**Comment by georgemccabe** [comment]
The tests for this wrapper were refactored as part of the work for #672
