### ISSUE TITLE
Change %H for level/lead for StringSub to default to 2 digit precision

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#275]
%H used in datetime automatically enters the date with 2 digit precision. When setting values for lead or level (input is int), %H defaults to 1 digit. The user can set %2H or %HH to force 2 digit precision. The default behavior of %H should pad 2 digit precision. If the user needs to force 1 digit precision, they can do so by using %1H.

**Comment by georgemccabe** [comment]
May be related to #276.

Currently for offset items (lead, level, etc.) StringSub formats %H %M and %S with one digit precision and only outputs the full number of the value, not relative to the other items. For example, if 120 seconds is formatted, %M will output 2 and %S will output 120. We should align this with the datetime functionality so that %M%S would output 0200.

Are there % options for what datetime expects to specify the full number of minutes instead of relative to the hour? For example, 90 minutes formatted with %H%M should be 0130, but we may want to output 90, the full number of minutes.

**Comment by georgemccabe** [comment]
Here is the list of supported % options for python strftime: http://strftime.org
There is no option to specify all minutes (i.e. 90). %s can currently be used to specify total seconds and %S to specify relative seconds. We should come up with a good way to notation that we want full minutes (> 59) and hours (>23)

**Comment by georgemccabe** [comment]
See 2nd section from this page: https://stackoverflow.com/questions/8906926/formatting-timedelta-objects

There are suggestions to writing a string formatter for timedelta objects by defining our own keywords or % identifiers.

**Comment by georgemccabe** [comment]
The most common format for specifying level or lead has been hours which can go above 23, so it seems like %H should still be used for this (default 2 digit precision, %1H, %3H, etc. to designate other precision. However, this differs from the strftime %H (00-23).

**Comment by georgemccabe** [comment]
We discussed in an engineering meeting that the current implementation of handling H, M, and S (each outputs the full number of units, not relative to next highest unit) is sufficient for the use cases we will likely encounter. We can revisit if we come across another use case that requires more support.

The change will likely go in the format_one_time_item function in the string sub code. We will need to write pytests to check various inputs to this function to ensure everything works smoothly.

**Comment by hankenstein2** [comment]
Added pytest for testing format_one_time_item. Can be expanded in the future if the functionality of %H etc needs to be expanded
