### ISSUE TITLE
ExtractTiles check for empty dirs bug

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#277]
ExtractTiles calls TcPairs wrapper and checks if the input directory is empty and exits if it is empty. However, a dated subdirectory can exist in this directory and this check will pass even though that directory is empty. TcPairs is attempted to run with no files in the list so the -lookin flag has no argument, so it fails. Instead of checking if the dir is empty, we should add a check to see if the file list is empty and error or warn and exit instead of running tc_pairs with an incorrectly formatted command.

**Comment by bikegeek** [comment]
We will need to check if the file size exceeds 703 bytes because the header
is created in the .tcst file


---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
Another thing to consider is that extract tiles can create numerous files,
some with just the header and others with the header and matched pairs.

---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
The extract tiles wrapper invokes the **tc-stat tool via the TcStat wrapper** but first checks that the tc-pairs output left behind by invoking the MET tc-pairs tool (via METplus TcPairs wrapper) has created any output.  There are some instances where there are dated subdirectories created by the TcPairs wrapper with no .tcst files as output.  Currently, there is only a check for the empty tc-pairs output directory.  Change the check for util.is_dir_empty to obtain a list of all files and check for non-zero number of files instead.  Problem has been reproduced, creating the following error message from the MET tc-stat tool:

_ERROR  :
ERROR  : process_command_line(int argc, char **argv) -> You must specify at least one source using the "-lookin" option.
ERROR  :

*** Model Evaluation Tools (METV8.1.1) ***

Usage: tc_stat
        -lookin source_

**Comment by bikegeek** [comment]
Now we get a list of all files in all dirs and if empty, log an error message indicating that no .tcst files exist, then exit.  If .tcst files exist, proceed as usual using these files as arguments to the -lookin flag and  invoke tc_stat.
