### ISSUE TITLE
Documentation: Add a dedication to all of the User's Guides

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplus#2780]
## Describe the Task ##
After the passing of Randy Bullock, Venita Hagerty, and Tara Jensen it was decided as a group to have a [dedication](https://docs.google.com/document/d/1UwL_nk2dlzHH9AKSsBkCVoRfZPhHe0lHesEOihS3W14/edit?tab=t.0) for all of the User's Guides.  Please name this section "In Memoriam".

Refer to each issue  in the separate repositories with the branch name, "feature_metplus_2780_dedication" so that the work has a paper trail to this issue.

Please add to ALL of the User Guides index at the top of the page.  Put it above "History".
[METplus](https://metplus.readthedocs.io/en/develop/index.html)
[MET](https://met.readthedocs.io/en/develop/index.html)
[METplotpy](https://metplotpy.readthedocs.io/en/develop/index.html)
[METcalcpy](https://metcalcpy.readthedocs.io/en/develop/index.html)
[METdataio](https://metdataio.readthedocs.io/en/develop/index.html)
[METviewer](https://metviewer.readthedocs.io/en/develop/index.html)
[METexpress](https://metexpress.readthedocs.io/en/development/index.html)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state today or tomorrow. Nov 12th, 2024.*

### Funding Source ###
*NOAA Base 2782544.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Review default **alert** labels
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Milestone and Projects ###
- [X] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@michelleharrold What sort of title should we give this section?
"In Memoriam" or "Dedication" or "Dedication In Memoriam" or something else entirely?

**Comment by lisagoodrich** [comment]
@jprestop is it okay to close this issue?

**Comment by jprestop** [comment]
@lisagoodrich Yes, please!  I'm so awful about remembering to close issues.  Thank you for catching this!

**Comment by lisagoodrich** [comment]
@jprestop thanks for confirming it is okay to close this issue.
