### ISSUE TITLE
Create a wrapper to custom ingest using python embedding

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#281]
We need a new wrapper to allow users to create a python script to ingest data into the format that MET expects. 
- The wrapper could be called CustomIngest and can be configured to read in multiple input/output/script configurations so the user can run multiple ingesters to get all of their data into a format that MET can process.
- Each ingester can be setup to call regrid_data_plane to get the data into a NetCDF file.
- Each ingester will need to know the python script to use, the input directory and/or template to read from, the output directory/template to write, and some way to specify the grid to map the data to. This could be a filename or a grid definition. Unless the attrs dictionary from the python script can be used to map the data automatically?

**Comment by georgemccabe** [comment]
We want to allow all wrappers for MET tools that support Python Embedding for input to support this functionality as well. Adding this functionality will guide how the custom ingest wrapper will be designed. It makes sense to create this wrapper instead of just having them use the RegridDataPlane wrapper because they may to convert more data than just forecast and observation data (i.e. climo, point obs, etc.).

**Comment by georgemccabe** [comment]
#211 handles python embedding for all apps, this focuses on the custom ingester wrapper

**Comment by georgemccabe** [comment]
Implemented CustomIngest wrapper and was able to generate commands calling regrid_data_plane using python embedding scripts for input. The script used was fake so it didn't actually work, but it generated the command the way it should be generated. We need a good use case to test that the behavior works correctly. I think the scripts on the DTC webpage require python with an hdf library that doesn't exist on the version of python that is used for the MET tools currently. We may need to wait until MET 9.0 is available to test. Also need to update documentation with the new config variables and a section describing the new wrapper.

**Comment by JohnHalleyGotway** [comment]
Tina will test this and coordinate with George.

**Comment by georgemccabe** [comment]
Upon review it appears that Python version conflicts cause python embedding scripts to fail, even if they only import numpy and set variables met_data and attrs. Testing this issue has to wait until MET is updated to handle python embedding with user defined python.

**Comment by georgemccabe** [comment]
CustomIngest wrapper now has a working use case using 2 different python scripts to generate NetCDF files.
