### ISSUE TITLE
Transition documentation from Lyx to Sphinx

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#297]
We currently use Lyx (a LaTeX-based GUI for documentation) to document METplus. We will be moving to using Sphinx, which uses RST (reStructuredText) formatted files to render documentation.

reStructuredText: http://docutils.sourceforge.net/rst.html
Sphinx: http://www.sphinx-doc.org/en/master/

@jprestop converted most of the current Lyx documentation to RST files using Pandoc (https://pandoc.org/). These will provide the baseline for the new documentation.

We will perform the initial configuration/RST development in a feature branch that will be merged with the develop branch ahead of the METplus-3.0 release. The documentation will then be available online at:
https://ncar.github.io/METplus

**Comment by DanielAdriaansen** [comment]
This is mostly complete, as there now exists Sphinx documentation for developers to edit in the develop branch. Remaining items:

1. Decide upon string formatting for keywords used for searching
2. Decide where to host quick reference page using keywords
3. Remove RST files that were created from Lyx in docs/Users_Guide
4. Remove doc/METplus_Users_Guide directory containing Lyx and PDF files
5. Merge existing parm/use_cases/* into either parm/use_cases/model_applications or parm/use_cases/met_tool_wrapper
6. Create a PDF
7. Figure out what to do with deprecated conf items in the glossary
8. Update contributors guide for documenting use case
9. Review documentation on how to update Sphinx documentation

**Comment by georgemccabe** [comment]
@DanielAdriaansen  can this issue be closed?

**Comment by DanielAdriaansen** [comment]
> @DanielAdriaansen can this issue be closed?

Yes! METplus v3.0 now includes documentation in Sphinx.
