### ISSUE TITLE
from __future__ imports need to be removed from python 3.6 code

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#302]
The from __future__ import (a,b,c) is no longer necessary, now that we have migrated to Python 3.  The __future__ is something that is found in Python3 to allow Python2 users to use Python3 features.

**Comment by georgemccabe** [comment]
On a similar note, any use of super no longer requires the class name and self. 

OLD:        c_dict = super(ModeWrapper, self).create_c_dict()
NEW:        c_dict = super().create_c_dict()

Are there any clean up to do in result of the move from python 2 to 3?

**Comment by georgemccabe** [comment]
Changes made in branch feature_302_remove_future_imports. Still need to merge into develop and test.

**Comment by georgemccabe** [comment]
Any 'from future imports' call has been removed from the METplus wrappers. This has been tested and merged into develop.
