### ISSUE TITLE
Enhancement to online user tutorial

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#303]
Jun Wang,  a visitor from SWPC (Space Weather Prediction Center) was following the instructions for the online METplus tutorial and had a few suggestions that address issues he had: 

For instance, he was unsure as to what he was supposed to set the METPLUS_PARM directory.
He also needed a syntax example for setting the environment variables in his profile, since he was unfamiliar with bash commands.

On the whole, he thought the documentation was clear.

**Comment by TaraJensen** [comment]
Closing - outdated feedback - will not fix
