### ISSUE TITLE
Consistent wrapper naming

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#304]
* Should match MET naming except dashes are not allowed in python class names, i.e. PCP-Combine => PCPCombine (currently PcpCombine) and Grid-Stat => GridStat, ASCII2NC => ASCII2NC (currently Ascii2Nc)
* We should make each item in PROCESS_LIST case insensitive to reduce user error.
* We could also support dashes and underscores by stripping them out
* We will need to create a dictionary that maps each name in all lower case with dashes and underscores stripped out to the correct camel-case notation to be able to find the correct wrapper.

'gridstat' => 'GridStat'
'ascii2nc' => 'ASCII2NC'
etc.

**Comment by georgemccabe** [comment]
This has been implemented, but we need to write a test for met_util's get_process_list function to make sure different combinations of inputs to PROCESS_LIST are handled correctly.

**Comment by georgemccabe** [comment]
Also need to update documentation to use the correct names.

**Comment by georgemccabe** [comment]
@fisherhucar , did you write the test for this issue and update the documentation?

**Comment by hankenstein2** [comment]
I have not written the test or updated the documentation and will move this to the next release.

**Comment by georgemccabe** [comment]
Unit tests for get_process_list have been written. We still need to review the documentation and change wrapper names to the correct naming. For example, in the Glossary and Python Wrappers pages, TcStat should be TCStat.
