### ISSUE TITLE
Enhance pcp_combine functionality to handle dumping the precip accum bucket frequency

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#305]

**Comment by georgemccabe** [comment]
This functionality has been added via branch feature_305_bucket_precip and has been merged into develop. Still need to update documentation to add FCST_PCP_COMBINE_BUCKET_INTERVAL and update FCST_PCP_COMBINE_INPUT_ACCUMS to mention that {lead} can be used as an item in this list and _BUCKET_INTERVAL will reset the value.

**Comment by georgemccabe** [comment]
Documentation has been updated in the branch feature_297_sphinx_transition. These changes will be merged into develop by Dan.
