### ISSUE TITLE
Rename config variables so that they contain the wrapper name

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#306]
We need to rename config variables so that it is clear where they are used if they are used exclusively in a given wrapper. For example, GENERATE_TRACK_ASCII is used only in CyclonePlotter. It should be named something like CYCLONE_PLOTTER_GENERATE_TRACK_ASCII.

Files that need review/updates:

cyclone_plotter_wrapper.py
extract_tiles_wrapper.py
make_plots_wrapper.py
series_by_init_wrapper.py
series_by_lead_wrapper.py
stat_analysis_wrapper.py
tcmpr_plotter_wrapper.py
tc_stat_wrapper.py

We should attempt to get this done for the 3.0 release so there will be minimal deprecated config variables going forward.

**Comment by malloryprow** [comment]
stat_analysis_wrapper.py and make_plots_wrapper.py will be renamed config variables and cleaned up when feature_226_stat_analysis_cleanup gets into develop.

**Comment by georgemccabe** [comment]
Great! It looks like tc_stat_wrapper.py already conforms to the naming convention.

I will take a look at:

series_by_init_wrapper.py
series_by_lead_wrapper.py

The following are still unclaimed:

cyclone_plotter_wrapper.py (Minna)
extract_tiles_wrapper.py
tcmpr_plotter_wrapper.py (Minna)

**Comment by georgemccabe** [comment]
I have made the config changes for SeriesByLead, SeriesByInit, and ExtractTiles. I still need to run the rest of the tests and update documentation.

**Comment by bikegeek** [comment]
Subissue created:
Github Issue #320 (cyclone plotter wrapper)

**Comment by georgemccabe** [comment]
It looks like all of the sub-issues have been closed, so I am going to close this ticket. Please reopen if you have not yet completed any work that needs to be done for this issue.
