### ISSUE TITLE
Refactor series by lead animation logic

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#336]
Extracting the 'TODO' in the create_animated_gifs() method in series_by_lead_wrapper.py (as added by Jim Frimel):
                # TODO:
                    # Fix animate_cmd so it does not require run_inshell
                    #  to work.
                    # It is working as is, ideally we do not require
                    # run_inshell
                    # The issue has to do with multiple files in the directory
                    # when using the wild card. If only one file exists
                    # then the command will run ok without run_inshell.
                    # You can repeat the issue
                    # by removing run_inshell keyword in the call below and
                    # running examples/custom_series_by_lead_all_fhrs.conf use case.
                    # no animated gifs are created.
                    # convert: unable to open image
                    # .... No such file or directory
                    #  @ error/blob.c/OpenBlob/2712.
                    # convert: unable to open file
                    # convert: no images defined

**Comment by georgemccabe** [comment]
This was completed with work for #310
