### ISSUE TITLE
Check if ncap.nc file exists before calling ncap2 in series_by_lead_wrapper.py

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#340]

**Comment by bikegeek** [comment]
From Jim Frimel's earlier comments in the series_by_lead_wrapper.py and George's recent run-ins, when you re-run without cleaning up your workspace and NCO's ncap2 tool has been run then the feature relative use case is re-run (due to premature termination, user stops it prematurely, failure, etc), you will see the following error:

---------------------------snip---------------------------------------------------
12/17 17:32:16.166 metplus.SeriesByLead (command_runner.py:89) INFO: RUNNING: /usr/local/nco/bin/ncap2 -v -s "max=max(series_cnt_TOTAL)" /d1/mccabe/out2/series_analysis_lead/series_F036/series_F036_TMP_P850.nc /d1/mccabe/out2/series_analysis_lead/series_F036/nseries.nc
ncap2: /d1/mccabe/out2/series_analysis_lead/series_F036/nseries.nc exists---`e'xit, `o'verwrite (i.e., clobber existing file), or `a'ppend (i.e., replace duplicate variables in, and add metadata and new variables to, existing file) (e/o/a)?


Here is Jim's comments from a few years ago:
----------------------snip----------------------------

# TODO: critical. harden Do we ant to add -O overwrite option to
# all ncap2 commands?? If I restart and not delete output
# the user is prompted. This will pause any automation

**Comment by georgemccabe** [comment]
This previously only happened when a run was restarted after failing in the middle and the files were already created. However, this now occurs on a fresh run. I modified the calls to ncap2 to overwrite the files if they already exist. This is a temporary solution to allow the use cases to run as expected in the upcoming release. These wrappers are due for a refactor to make them more efficient, conform to the format of the other wrappers, and reduce the number of redundant calls. This is documented in issue #342
