### ISSUE TITLE
Consolidate MET config file used by series by lead and series by init wrappers

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#345]

**Comment by bikegeek** [comment]
The feature relative use case for performing series analysis by lead time and by init time are both using the SeriesAnalysisConfig_by_init MET config file.  The SeriesAnalysisConfig_by_init and SeriesAnalysisConfig_by_lead config files differ by only a whitespace.

**Comment by georgemccabe** [comment]
This was completed with work for PR #747
