### ISSUE TITLE
Migrate multiple use case wrappers to the new directory structure

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#346]
Restructure the METplus/parm/use_cases directory to include the following sub-directory structure:

METplus/parm/use_cases/model_applications/medium_range
METplus/parm/use_cases/model_applications/tc_and_extra_tc
... etc.  (see below for the subdirectories)

(see METplus wrapper and repo notes for December 19, 2019
-------------snip------------
Medium_range
feature_relative/feature_relative.conf
feature_relative/examples/series_by_init_12-14_to_12-16.conf
feature_relative/examples/series_by_lead_all_fhrs.conf
feature_relative/examples/series_by_lead_by_fhr_grouping.conf
grid_to_grid/grid_to_grid.conf
grid_to_grid/examples/anom.conf
grid_to_grid/examples/anom_height.conf
grid_to_grid/examples/gather_all_dates.conf
grid_to_grid/examples/gather_by_date.conf
grid_to_grid/examples/sfc.conf
grid_to_obs/grid_to_obs.conf
grid_to_obs/examples/conus_surface.conf
grid_to_obs/examples/gather_all_dates.conf
grid_to_obs/examples/gather_by_date.conf
grid_to_obs/examples/upper_air.conf
S2s
Dan to add pwat and rh use cases
convection_allowing_models
hwt/examples/HREFv2.conf
hwt/examples/HREFv2_ens.conf
hwt/examples/HRRRe.conf
hwt/examples/HRRRe_ens.conf
hwt/examples/HRRRv3.conf
hwt/examples/HRRRv4.conf
hwt/examples/NSSLfv3.conf
hwt/examples/base_paths.conf
hwt/examples/bigbang.conf
hwt/examples/ens_stat.conf
hwt/examples/grid2grid_hwt_env.conf
ensemble/examples/hrrr_ensemble_sfc.conf
ensemble/examples/hrrr_ensemble_sfc_wildcard.conf
ensemble/examples/hrrr_pb2nc.conf
ensemble/examples/hrrr_ensemble_sfc.conf
ensemble/examples/hrrr_ensemble_sfc_wildcard.conf
ensemble/examples/hrrr_pb2nc.conf
tc_and_extra_tc
cyclone_plotter/cyclone_plotter.conf
track_and_intensity/track_and_intensity.conf
space_weather
swpc use-cases
marine
cryosphere
coastal
air_quality
pbl
land_surface
extremes
climate
precipitation
hmt/examples/href-mtd.conf
hmt/examples/href-vs-href.conf
hmt/examples/hrrr_exp-mtd.conf
hmt/examples/hrrr_exp-vs-hrrr_exp.conf
hmt/examples/hrrre-vs-hrrre-prob.conf
hmt/examples/hrrre-vs-hrrre.conf
hmt/examples/phpt-mtd.conf
hwt/examples/ens_mean_apcp24.conf
hwt/examples/ens_mean_apcp3.conf
hwt/examples/ens_stat_apcp24.conf
hwt/examples/ens_stat_apcp3.conf
hwt/examples/HREFv2_ens_apcp24.conf
hwt/examples/HREFv2_ens_apcp3.conf
hwt/examples/HRRRe_ens_apcp24.conf
hwt/examples/HRRRe_ens_apcp3.conf
grid_to_grid/examples/precip.conf
grid_to_grid/examples/precip_continuous.conf
grid_to_grid/examples/precip_continuous_zero_accum.conf
miscellaneous

**Comment by bikegeek** [comment]
George is going to experiment with one of the use cases in the 'develop' branch of the repository, and then let Tara take a look and verify if this is the desired organizational structure.

**Comment by bikegeek** [comment]
Sub-Issue GitHub #347 for migrating the following to 'medium_range' sub-directory:
feature_relative/feature_relative.conf
feature_relative/examples/series_by_init_12-14_to_12-16.conf
feature_relative/examples/series_by_lead_all_fhrs.conf
feature_relative/examples/series_by_lead_by_fhr_grouping.conf

**Comment by bikegeek** [comment]
Here is how we assigned the tasking (taken from the 20191223 METplus Engineering Topics meeting notes: https://docs.google.com/document/d/1bDX64UnsUVgXLVHZjalEJOGcZQdeB6L9meDTLE42xGs/edit#):


===================================
Rearranging use case subdirectories:
grid_to_grid (Mallory)
grid_to_obs (George)
qpf (George)
These go under precip
feature_relative (Minna)
track_and_intensity (Minna)
hwt (Hank)
hmt (George)
The MODE examples just compare a model to itself, so only move the MTD examples
ensemble (Jim)
cyclone_plotter (Minna)
mode (George)
noaa (George)
plotting (Minna)
py_embed (George)
wrappers (George)

**Comment by georgemccabe** [comment]
The use cases are now in the new directory structure. We still need to rename the use cases (another ticket #371 ), but I am closing this ticket.
