### ISSUE TITLE
Migrate track and intensity use cases to new directory structure

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#348]

**Comment by bikegeek** [comment]
This is a sub-issue of GitHub Issue #346.  Move the track and intensity use case files from the METplus/parm/use_cases/track_and_intensity directory to the METplus/parm/use_cases/model_applications/tc_and_extra_tc directory.

**Comment by bikegeek** [comment]
tcmpr_mean_median_box.py, tmcmpr_mean_median_box.conf (replaces tcmpr_mean_median.conf and track_and_intensity.conf), tc_stat_filter.py and tc_stat_filter.conf now in the METplus/parm/use_case/model_applications/tc_and_extra_tc directory

**Comment by georgemccabe** [comment]
@bikegeek , can this be closed?

**Comment by bikegeek** [comment]
Updates merged into the develop branch.
