### ISSUE TITLE
Add scientific objective information to each use case documentation file

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#349]
I will create a list of use case files that still need science review to complete. Input for the header, Scientific Objective, Datasets sections (and any other that may need more information).

**Comment by georgemccabe** [comment]
All of the following files can be found in the develop branch and are in met_tool_wrapper directory unless otherwise specified. When completed, add your name and any notes next to the filename.

ASCII2NC.py - [x]sci input and review
CyclonePlotter.py - [x]sci input and review
EnsembleStat.py - [x]sci input and review
Example.py - [x]sci input and review
GridStat.py - [x]sci input and review
MODE.py - [x]sci input and review
MTD.py - [x]sci input and review
PB2NC.py - [x]sci input and review
pcp_add.py - [x]sci input and review
pcp_bucket.py - [x]sci input and review
pcp_custom.py - [x]sci input and review
pcp_derive.py - [x]sci input and review
pcp_python_embedding.py - [x]sci input and review
pcp_subtract.py - [x]sci input and review
pcp_sum.py - [x]sci input and review
PointStat.py - [x]sci input and review
RegridDataPlane.py - [x]sci input and review
SeriesByInit.py - [x]sci input and review
SeriesByLead.py - [x]sci input and review
StatAnalysis.py - [x]sci input and review
TCMPRPlotter.py - [x]sci input and review
TCPAirs_A.py - [x]sci input and review
TCPairs_B.py - [x]sci input and review
TCStat.py - [x]sci input and review


medium_range/anom.py - [x]rename [x]sci input and review
medium_range/conus_surface.py - [x]rename [x]sci input and review
medium_range/feature_relative.py - [x]rename [x]sci input and review
medium_range/series_by_lead_by_fhr_grouping.py - [x]rename [x]sci input and review
medium_range/sfc.py - [x]rename [x]sci input and review
medium_range/upper_air.py - [x]rename [x]sci input and review

precipitation/hrefmean-vs-s4gempak.py - [x]rename [x]sci input and review
precipitation/phpt-mtd.py - [x]rename [x]sci input and review
precipitation/phpt-vs-s4grib.py  - [x]rename [x]sci input and review
precipitation/precip.py - [x]rename [x]sci input and review

convection_allowing_models/href-mtd.py - [x]rename [x]sci input and review
convection_allowing_models/hrrr_ensemble_sfc.py - [x]rename [x]sci input and review

tc_and_extra_tc/cyclone_plotter.py [x]rename [x]sci input and review
tc_and_extra_tc/tcmpr_mean_median_box.py - [x]rename [x]sci input and review

s2s/seasonal_forecast.py - [x]rename [x]sci input and review
space_weather/glotec_vs_glotec - [x]rename [x]sci input and review

**Comment by georgemccabe** [comment]
A review of the existing model application use cases could be useful before delegating files to document as some of the use cases may be similar to other cases and not necessary to include. For example, ruc-vs-s2grib and phpt-vs-s4grib both run PCPCombine, RegridDataPlane, and GridStat, but phpt-vs-s4grib uses probabilistic forecast data as input, so both of these cases should likely be included. precip.conf runs PCPCombine and GridStat, but it is similar to ruc-vs-s2grib so it may not need to be included. precip_continuous just runs PCPCombine in SUBTRACT mode, which is already demonstrated in met_tool_wrapper/PCPCombine_C.

Other cases that may be redundant:
In medium_range directory
anom.conf -- just runs GridStat
anom_height.conf - just runs GridStat
sfc.conf - just runs GridStat
conus_surface.conf and upper_air.conf -- both run PB2NC > PointStat

**Comment by georgemccabe** [comment]
I added TCPairs_B.conf to met_tool_wrapper because this case demonstrates looping over run times and processing HWRF data. The other TCPairs use case in that directory processes SBU data (runs a reformatter to get it into ATCF format) for all run times.

**Comment by georgemccabe** [comment]
model_applications/medium_range/anom.py now exists and needs scientific input.

**Comment by georgemccabe** [comment]
conus_surface.py and upper_air.py now exist in model_applications/medium_range and need scientific input.

**Comment by j-opatz** [comment]
Updated Jan 7 comment with uses cases included in 3.0. New issue will be developed for engineering input and review on close of this issue.

**Comment by j-opatz** [comment]
All scientific objectives have been added or updated as necessary.
