### ISSUE TITLE
Migrate the cyclone plotter use cast to model_applications subdirectory

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#352]
This is a sub issue of GitHub issue #346, move the existing METplus configuration file to the METplus/parm/use_cases/model_applications/tc_and_extra_tc directory, and create a corresponding Sphinx gallery document

**Comment by georgemccabe** [comment]
@bikegeek , can this issue be closed? It looks like the files have been moved over and docs updated.

**Comment by bikegeek** [comment]
Updates merged into develop branch.
