### ISSUE TITLE
Create StatAnalysis met_tool_wrapper use case

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#356]
Use met_test data and recreate a command from the MET make tests if possible. Also add documentation.

**Comment by georgemccabe** [comment]
I created this use case based on gather_by_date.conf previously in grid_to_grid. I modified the use case to read grid_stat output that is found in the met_test directory. However, the configuration removes all input, so it needs to be modified to be able to read and process this data. This could be as simple as changing the init or valid times that it allows.

**Comment by georgemccabe** [comment]
@jimfrimel modified the StatAnalysis.conf file to resolve the issue.

**Comment by jimfrimel** [comment]
Updated the StatAnalysis Single Wrapper Use Case sphinx documentation.
see commit: 3577cc02f2b
