### ISSUE TITLE
Use cases with external dependencies

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#365]
Note to Jim and Minna - I assigned both of you because I think either of you are familiar enough with the SeriesBy* cases to take care of this. You can either claim it or talk to someone else about handling it if you are unable to.

We currently have some use cases that use external dependencies and will potentially have more in the future. These currently include the SeriesBy* use cases (that use [exe] items like ncap2, ncdump, etc.) and the Gempak use cases that required GempakToCF (previously in qpf directory).

For these cases, we need to:

1) Make sure the .py documentation file for these cases clearly mention that there are external dependencies that are needed

2) Make sure the wrappers that require these tools check in the initialization step that if an external tool is going to be used in the use case, it has access to the tool and is properly configured to use it.  (I think this may be already done for SeriesBy*, but we should make sure). The wrapper should report a useful error mentioning the external tool that is required, what configs to set, and/or where to obtain more information about getting the tool. self.isOK should be set to False so the wrapper execution does not continue.

**Comment by georgemccabe** [comment]
Update: I modified getexe to return None if the executable was not found correctly instead of calling exit(1). This was only called in the SeriesBy* wrappers, so I added checks in the init function for each of the exes needed by the wrapper and set self.isOK to False if any were not found. Moved getexe call in SeriesByInit to the init function so it will be caught in that stage instead of when running.

Added a function to verify externals which currently only calls a function to check gempak. This function is called in CommandBuilder init after create_c_dict (for all wrappers). The function gets all of the c_dict values that end with TEMPLATE to check if any of them end in .grd and gets all of the c_dict values that end with DATATYPE to check if any of them are set to GEMPAK. If any of these cases are found, it will check that [exe] GEMPAKTOCF_JAR is set and if the path exists, reporting an error if it is not. The same check for the jar file is done in the GempakToCF wrapper, so all cases where Gempak data will be used but METplus is not configured to read it will error early and clearly.

All pytests passed, currently running use case tests. Once I confirm everything passes I will merge to develop. I still need to update the .py documentation files that use Gempak data to clearly mention that the jar file needs to be set correctly and point the user to where they can download it.

**Comment by bikegeek** [comment]
On 2/05/2020, Updated the documentation for feature_relative.py, series_by_init_12-14_to_12_16.py, series_by_lead_all_fhrs.py, and series_by_lead_by_fhr_grouping.py and committed to develop branch.

**Comment by georgemccabe** [comment]
GempakToCF.py is created with instructions on how to obtain the jar file needed for Gempak support and how to configure METplus to find the file. Error message if GEMPAKTOCF_JAR is not set correctly mentions to check that py file for information on obtaining and configuring it. We need to include a note in the other 2 use cases that use Gempak data to mention to refer to GempakToCF.py to configure Gempak support.

convection_allowing_models/href-mtd.conf
precipitation/hrefmean-vs-s4gempak.conf

**Comment by georgemccabe** [comment]
This work has been completed.
