### ISSUE TITLE
Update regrid_data_plane wrapper to support -gaussian_dx and -gaussian_radius command line options in met-9.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#367]
Jeff Hamilton raised the following issue via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=94050

"One thing I'll note, the METplus regrid_data_plane wrapper does not support
the Gaussian method (specifically adding gaussian_dx and gaussian_radius as
argument options). I'm sure that is on the to-do list for future versions,
but it would be nice to have at some point. In the meantime I have a
workaround in place."

Comparing the usage for regrid_data_plane between met-8.1 and met-9.0, you can see there's 2 new command line options:

*** Model Evaluation Tools (METV8.1.1) ***Usage: regrid_data_plane input_filename to_grid output_filename -field string [-qc flags] [-method type] [-width n] [-sigma n] [-shape type] [-vld_thresh n] [-name list] [-log file] [-v level] [-compress level]

*** Model Evaluation Tools (METV9.0) ***Usage: regrid_data_plane input_filename to_grid output_filename -field string [-method type] [-width n] [-gaussan_dx n] [-gaussan_radius n] [-shape type] [-vld_thresh n] [-name list] [-log file] [-v level] [-compress level]

**Comment by georgemccabe** [comment]
REGRID_DATA_PLANE_GAUSSIAN_DX and REGRID_DATA_PLANE_GAUSSIAN_RADIUS are now config variables that can be set to set the -gaussian_dx and -gaussian_radius command line args respectively. If unset or set to a blank string, they will not be added to the command.
