### ISSUE TITLE
Rename use cases

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#371]
We need to rename the use cases so that they fit a standard with descriptive names. John O. has created a list of name changes.

**Comment by georgemccabe** [comment]
I am starting on the convection_allowing_models use cases.

**Comment by j-opatz** [comment]
Beginning name changes for medium range use cases.

**Comment by georgemccabe** [comment]
Finished convection_allowing_models use cases. Moving on to precipitation.

**Comment by georgemccabe** [comment]
Finished precipitation cases except for precip_continuous.conf and ruc-vs-s2grib.conf since we haven't decided on what to do with these cases.

Moving on to s2s and space_weather.

**Comment by georgemccabe** [comment]
Finished s2s and space_weather, on to tc_and_extra_tc

**Comment by georgemccabe** [comment]
Finished tc_and_extra_tc except for tc_stat_filter.conf since we haven't decided on what to do with this case.

**Comment by j-opatz** [comment]
Finished Medium range use cases

**Comment by georgemccabe** [comment]
All of the use cases are now named following the new standard.
