### ISSUE TITLE
Automate links in the User's Guide to the Glossary

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#372]
Write a script to modify the documentation to create a link for each of the variables in the Python Wrappers section of the User's Guide to link to the variables in the Configuration Glossary (or see if Sphinx can do this automatically)

**Comment by DanielAdriaansen** [comment]
Are you thinking of having a script run and check the Python Wrappers section against a database of glossary terms, or are you trying to find a way to link to the glossary when writing the RST/updating the Python Wrappers RST? If the latter, then check out the :term: role:
https://www.sphinx-doc.org/en/1.5/markup/inline.html#role-term

**Comment by georgemccabe** [comment]
This issue can be closed. The list of variables in the Python Wrappers chapter uses the :term: keyword that was mentioned by Dan in the above comment. A warning is output when building the docs if any variable listed in the Python Wrappers chapter is not found in the glossary.
