### ISSUE TITLE
Support Python Embedding input to SeriesAnalysis, MTD, and EnsembleStat

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#381]
Using Py embedding to pass input for multiples files is now supported in these MET tools, but modifications to METplus are needed to support these cases.

MTD and EnsembleStat should be able to support it by adding environment variables FCST_FILE_TYPE and OBS_FILE_TYPE that will be set inside the fcst and obs dictionaries respectively. These should normally be set to an empty string, but if Python Embedding is used in these cases, they should be set to a string to sets the file type to the correct type of input, i.e.:

file_type = PYTHON_NUMPY;

If this is set, the field name passed to the tools can be set to the python call, i.e.:

{ name="read_CPC_binary.py MET_PYTHON_INPUT_FILE 10" }

which will substitute each file name listed in the file list for MET_PYTHON_INPUT_FILE. This should call the python embedding scripts multiple times with the correct inputs for each.

SeriesAnalysis will need additional refactoring to support this because the NAME and LEVEL environment variables are used like this:

fcst = {

   field = [
      {
        name  = "${NAME}";
        level = [ "${LEVEL}" ];
      }
   ];

}
obs = fcst;

We could add the file type variable to tell it to use python embedding, but we will need to make setting 'level' optional and be able to set fcst and obs values separately so that one input can use python embedding and the other can not. Refactor of SeriesBy[Lead/Init] is described in GitHub issue #342

**Comment by georgemccabe** [comment]
MTD and EnsembleStat wrappers have been modified to support python embedding. There are use cases in the met_tool_wrapper section demonstrating how to run this way.

EnsembleStat/EnsembleStat_python_embedding.conf
MTD/MTD_python_embedding.conf

I wrote a SeriesAnalysis wrapper that just finds files and calls the tool without filtering. I created a use case demonstrating how to use this wrapper with and without python embedding

SeriesAnalysis/SeriesAnalysis.conf
SeriesAnalysis/SeriesAnalysis_python_embedding.conf

I still need to:

1) write doc files for each of the SeriesAnalysis use cases
2) Create section for SeriesAnalysis in the Python Wrapper section of the documentation
3) Add all new configs for SeriesAnalysis to the glossary

**Comment by georgemccabe** [comment]
John O. is working on the doc files for each SeriesAnalysis use case

**Comment by georgemccabe** [comment]
I finished to-do items 2 and 3.

**Comment by j-opatz** [comment]
Completed item 1, documentation for the SeriesAnalysis use case
