### ISSUE TITLE
Create gen_vx_mask wrapper

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#387]
## Describe the New Feature ##
We need to wrap the Gen-Vx-Mask tool for use in several use-cases.
One example is using data thresholding for given thresholds in the [Surrogate Severe](https://github.com/NCAR/METplus/issues/413) and [Practically Perfect](https://github.com/NCAR/METplus/issues/406) use-cases.  

Options that need to be included:
-type str
-input_field string
-mask_field string
-complement
-union | -intersection | -symdiff
-thresh string
-height n
-width n
-shapeno n
-value n
-name string

### Acceptance Testing ###
Input:  MET netCDF files - for example from the Regrid-Data-Plane tool
Test: Generate a mask using each of these options

### Time Estimate ###
1-2 days

### Relevant Deadlines ###
Need it for HWT so by 4/7 so the rest of the use-case can be built and tested

### Funding Source ###
2770471 - SWPC 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to other METplus components.
Delete items that do not apply.
- [X] Define new issue for METplus.
https://github.com/NCAR/METplus/issues/406
https://github.com/NCAR/METplus/issues/414

## New Feature Checklist ##
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_387_gen_vx_mask`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
George asked me to test if/how python embedding working gen_vx_mask.

(1) It does NOT work for the "-input_field" option.
```
[johnhg@number5]% /usr/local/met-9.0/bin/gen_vx_mask PYTHON_NUMPY data/poly/CONUS.poly test_input_field.nc -input_field 'name="scripts/python/read_ascii_numpy.py data/python/fcst.txt FCST";'
DEBUG 1: Input File:		PYTHON_NUMPY
DEBUG 1: Mask File:		data/poly/CONUS.poly
ERROR  : 
ERROR  : Met2dDataFile::grid() -> no grid defined!
ERROR  : 
```
(2) It also does NOT work for the "-mask_field" option.
```
[johnhg@number5]% /usr/local/met-9.0/bin/gen_vx_mask data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212 PYTHON_NUMPY test_mask_field.nc -mask_field 'name="scripts/python/read_ascii_numpy.py data/python/fcst.txt FCST";' -thresh gt0 -type data
DEBUG 1: Input File:		data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212
DEBUG 1: Mask File:		PYTHON_NUMPY
DEBUG 2: Parsed Data Grid:	Lambert Conformal (185 x 129)
ERROR  : 
ERROR  : Met2dDataFile::grid() -> no grid defined!
ERROR  : 
```

For GRIB1, GRIB2, and NetCDF files, once we call "open" on the input file, the grid is defined.  For python embedding, the grid is defined at the same time we read the data.  Logic could be added to make one or both of these options work with python embedding.  We'd just need to do that extra step of reading the data before trying to access the grid definition.

**Comment by georgemccabe** [comment]
Thanks for the info. I will still write the wrapper with support for string substitution for the current run time for these arguments so that when the python embedding support is available for them, the wrapper will already support it.

**Comment by JohnHalleyGotway** [comment]
sudo-calls for the gen_vx_mask wrapper to create:

INPUT_TEMPLATE=a/b/c
OUTPUT_TEMPLATE=x/y/z
MASK_OPTIONS='-type poly','-type LAT -thresh gt0', '-type LON -thresh gt-100&&lt<70', '-type SOLAR_AZI -thresh gt0'
// Must also be length 4
MASK_TEMPLATE='/path/to/CONUS.poly', 'a/b/c', 'a/b/c', '20180807_120000'

(1) gen_vx_mask a/b/c /path/to/CONUS.poly temp1.nc -type poly
(2) gen_vx_mask temp1.nc a/b/c temp2.nc -type LAT -thresh gt0
(3) gen_vx_mask temp2.nc a/b/c temp3.nc -type LON -thresh gt-100&&lt<70
(4) gen_vx_mask temp3.nc a/b/c x/y/z -type SOLAR_AZI -thresh gt0

**Comment by georgemccabe** [comment]
Wrapper has been developed and (mostly) tested. Added use cases to process a file with no arguments, a use case that runs the tool multiple times, creating temporary intermediate files to pass to the next call, and added use cases that runs the tool once and utilizes filename templates in the command line arguments. Need to verify that the tool meets the needs of the scientists that will be using it for their new use cases.
