### ISSUE TITLE
Disable download button at the bottom of each use case documentation file

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#399]
The links at the bottom of each use case will download the documentation file as a Python file or Jupyter notebook. This is misleading, as the user may think it is downloading the actual config file. We should remove these buttons. I believe this is a sphinx_gallery setting to add to the conf.py file in the docs directory. Setting this here should apply to all use cases in the entire User's Guide.

**Comment by georgemccabe** [comment]
Dan and I investigated this issue today. It turns out that the setting that sounded like it should remove these buttons does not actually do that. To remove these buttons, we would need to either:

* Write a script to remove the buttons from the HTML files after the documentation is built. We would likely write a build script that calls 'make clean html' on the documentation, then calls the script to remove the buttons. It could perform any other manipulation we want to the documentation files (like removing the tags that set the thumbnail image that is shown in the text).
We could also use this to build the doxygen output at the same time (which is currently done in a separate step).

* Modify the CSS for the webpage to hide the <div> blocks that contain the buttons.

**Comment by JohnHalleyGotway** [comment]
The first option sounds better thought out and less of a hack.  Perhaps the standard document rendering process gets us 95% of what we want, but we need to do some extra work for that last 5%.  Having a script to post-process and clean up the docs is fine.  And this would be one of those cleanup steps.  So the first option makes sense to me.

**Comment by TaraJensen** [comment]
I agree with John.  Thanks for looking into it.

**Comment by jimfrimel** [comment]
I think ... that may be ok also ...
My only comment would be to consider defining a unique clean target in the
Makefile, ie. clean_sphinx: ?
Jim

**Comment by georgemccabe** [comment]
Work done in feature_399_disable_download_buttons
