### ISSUE TITLE
Change mouse over text for use cases to include config file name

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#400]
Users have to open each use case listed in the User's Guide by clicking the icon and scrolling down to find the config file name that corresponds to it. At the METplus meetings on 3/19/2020, we discussed changing the use cases so that the mouse-over text (which is the text at the top of the use case py file within the triple quotes) to include the name of the config file that is used for the example. We noticed that the text falls off the edge of the pop-up bubble, so we should add line breaks appropriately so it is readable inside the bubble. For example:

GridStat_fcstHREFmean
_obsStgIV_NetCDF.conf

The text that was previously in the top section should be moved into the Scientific Objective section so it is preserved.

**Comment by TaraJensen** [comment]
Files to be edited are now located in METplus/docs/use_cases

**Comment by TaraJensen** [comment]
Done with met_tool_wrapper docs

**Comment by TaraJensen** [comment]
Done with model_applications docs, merged back into development
