### ISSUE TITLE
Adapting existing MET configs to work with METplus wrappers

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#401]
Address the use case when a user has an existing MET config file they'd like to use with METplus wrappers. 

Some questions:
1. Should the recommendation be for the user to "retrofit" METplus conf item environment variables into their configs so they can use METplus conf items to control aspects of their config? Or should the user take their settings in their file, and merge them into the MET config files shipped with METplus wrappers in parm/met_config which contain all the environment variables already?
2. Should we have a section in the documentation addressing the answer to question1?

**Comment by georgemccabe** [comment]
This was resolved in 4.0.0. See https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#overriding-unsupported-met-configuration-variables
