### ISSUE TITLE
Improve documentation on mapping METplus configuration items to MET config file env vars

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#402]
Add additional documentation, or re-work existing documentation that can help a user understand what environment variables are being set by METplus wrappers when a METplus conf item is set. George proposed putting this in the Python Wrappers section of the User's Guide. I also think the glossary could be updated to include the name of the environment variable set by the conf item, so as someone is "configuring" METplus and looking up items in the glossary there's a connection at that point for the user. @lisagoodrich may be able to help with the glossary work if that's the route we decide.

George also mentioned having a new DEBUG option that will print the METplus configuration items being used and the environment variables being set to logging somewhere.

**Comment by georgemccabe** [comment]
Consider creating a separate page to describe how each METplus config translates to the environment variable read by MET config files. We could link into this page from each use case doc and the Python Wrappers section of the User's Guide.

**Comment by DanielAdriaansen** [comment]
@georgemccabe would you agree this was handled via #768 and can be closed?

**Comment by georgemccabe** [comment]
I think so. The additions you made to the Python Wrappers section cover how the METplus configs correspond to the environment variables used in the wrapped MET configs and the MET config variables that they control. I added logic to print a WARNING message if any of the supported METPLUS_ environment variables are not used in the user's wrapped MET config so they are aware that they can switch to using the wrapped configs in parm/met_config.

**Comment by DanielAdriaansen** [comment]
Great, thanks!
