### ISSUE TITLE
Documentation lists conf files that have been renamed

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#410]
The following section lists conf files like feature_relative.conf that have been renamed for this release:

https://ncar.github.io/METplus/Users_Guide/installation.html#running-metplus-wrappers

## Describe the Problem ##
Examples need to be renamed to match actual file location
Usage statement (usage_wrapper.py) also contains old paths that should be updated.

### Expected Behavior ###
Documentation and usage statements reference the correct paths

### Environment ###
N/A

### To Reproduce ###
* Go to https://ncar.github.io/METplus/Users_Guide/installation.html#running-metplus-wrappers and make sure formatting is correct and text makes sense.
* Run master_metplus.py with a user config file (MET_INSTALL_DIR, INPUT_BASE, OUTPUT_BASE) and review usage statement output.

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

**Comment by georgemccabe** [comment]
[METplus-resolve-and-review-issues.txt](https://github.com/NCAR/METplus/files/4388506/METplus-resolve-and-review-issues.txt)

**Comment by j-opatz** [comment]
Both develop and Master_v3.0 branch have been successfully updated with pull requests.
