### ISSUE TITLE
Develop NRL Aerosol Use-Case

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#411]
## Describe the New Feature ##
We have a project with NRL to develop use-cases for Aerosol and Dust evaluation.  The first step is developing a python script to read in the observation and forecast data and pass into MET tools such as Grid-Stat and MODE.

### Acceptance Testing ###
Fcst Input:  ENAAPS and ICAP aerosol predictions
Obs Input: UW CIMSS federated data set
Source:  UW CIMSS data set on dakota at: /d3/personal/jensen/AGGR_HOURLY_20200124T0000_1deg_global_archive.nc
*Still need to get ENAAPS and ICAP grids*
Tests: Properly read analysis file, Grid-Stat and MODE runs successfully 

*Describe tests required for new functionality.*

### Time Estimate ###
As this task will require back and forth with NRL, time estimates vary from 2 to 3 weeks.
Initial week will focus on analyzing the data files and transferring them to a MET-friendly format.
Following work weeks will focus on use cases and specific statistic criterion.

### Relevant Deadlines ###
Should be done by 6/30/2020

### Funding Source ###
7730021 NRL Aerosol

### Assignee ###
- [ x] Select **engineer(s)** or **no engineer** required
- [ x] Select **scientist(s)** John Opatz

### Labels ###
- [x ] Select **component(s)**
- [x ] Select **priority**
- [ x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to other METplus components.
NONE

**Comment by j-opatz** [comment]
Progress as of 6/2:
Both observation and forecast files have been reviewed and, via a python script, converted into a MET-readable netCDF format. These new .nc files have been passed to GridStat and EnsembleStat (via wrappers) and sensible output produced.
Next steps include:

- Utilize Python embedding to pass memory-stored data sets to GridStat and EnsembleStat (as opposed to creating new netCDFs)
- Discuss opportunities to improve MET to directly interpret obs/fcst files, which will require var1(lon, lat) to be transposed to var1(lat, lon) internally, read multi-dimension arrays that contain members of an ensemble, and more
- Move onto examples that utilize MODE and MODE-TD

**Comment by j-opatz** [comment]
Further development on the uses cases have taken steps outlined in previous meeting. These include:

- Python embedding now interprets netCDF files, no longer requires intermediate file creation step
- MODE and MODE-TD have been explored, as well as Series Analysis, which brings total METplus tools used to
  1. GridStat
  2. EnsembleStat
  3. MODE
  4. MODE-TD (not effective tool for total aerosol optical depth mean)
  5. SeriesAnalysis

Use cases are now being readied for inclusion in the next beta release, which requires path changes to relative (vs absolute), updated code documentation for improved user experience, removing superfluous variables/commands, etc. Use cases already included in METplus archive will be used as guides, along with team suggestions/guidance.

**Comment by j-opatz** [comment]
PR was completed and use case is successfully integrated into the next beta release
