### ISSUE TITLE
Develop Surrogate Severe Calculation use-case

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#413]
## Describe the New Feature ##
1.  Use pcp_combine to create a 24 h maximum of max UH field
2.  Run Regrid-Data-Plane to NCEP 211 using max; width is 81.27; square of 27 grid boxes
**Plan to loop over multiple thresholds (that correspond to different percentiles)**
3.  Run gen-vx-mask to get a binary masking field
4.  Run Regrid-Data-Plane using max-gauss; width of 1 for smoothing only
5.  Run Plot-Data-Plane

### Acceptance Testing ###
Input: Any grid that has maximum Updraft Helicity
Sources: Burkely Gallo at SPC and HWT
Path: dakota:/d3/projects/MET/test_surrogate_severe/from_burkley_20200310
Tests:  Recreate Burkely's sample case

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
*Larger issues should be broken down into sub-issues.*

### Relevant Deadlines ###
Needed for HWT, so 4/20/2020 would be best

### Funding Source ###
2770041 - JTTI Hail Project (Lindsay, Hank, and Tina)

### Assignee ###
- [ x] Select **engineer(s)** or **no engineer** required
- [x ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ x] Select **component(s)**
- [x ] Select **priority**
- [x ] Select **requestor(s)**

### Projects and Milestone ###
- [x ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to other METplus components.
Related to [METplus Issue 405](https://github.com/NCAR/METplus/issues/405)
Related to [METplus Issue 406](https://github.com/NCAR/METplus/issues/406)

**Comment by lindsayrblank** [comment]
Thresholds and corresponding percentiles provided by Burkely Gallo from SPC. These are values of updraft helicity and are in m^2/s^2.
- 14.2 (75th percentile)
- 19.0 (80th percentile)
- 26.0 (85th percentile)
- 38.0 (90th percentile)
- 61.0 (95th percentile)

**Comment by lindsayrblank** [comment]
Notes from John Halley Gotway from 03/10/2020 where the group worked with Burkely Gallo to get the commands/steps to successfully produce surrogate severe data. 
[Surrogate_Severe_Notes.txt](https://github.com/NCAR/METplus/files/4390178/Surrogate_Severe_Notes.txt)

**Comment by lindsayrblank** [comment]
Burkely Gallo's surrogate severe Fortran code

[probs_ens_fv3.f90.txt](https://github.com/NCAR/METplus/files/4390396/probs_ens_fv3.f90.txt)
[probs_ens_HREFv2.f90.txt](https://github.com/NCAR/METplus/files/4390398/probs_ens_HREFv2.f90.txt)

**Comment by LoganDawson-NOAA** [comment]
This use case is also highly desired by EMC with the HREFv3 Evaluation beginning on May 4th. I'd be happy to assist with development and/or beta testing of the use case.
