### ISSUE TITLE
Develop Surrogate Severe Evaluation use-case

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#414]
## Describe the New Feature ##
Combination of the  Surrogate Severe and Practically Perfect Prog use-cases

### Acceptance Testing ###
Fcst Input: Any file with Updraft Helicity in it
Obs Input: Local Storm Report
Source:  Initially HWT
Test:  Use Burkely Gallo's examples to execute the evaluation

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
*Larger issues should be broken down into sub-issues.*

### Relevant Deadlines ###
Needed for HWT, so 4/20/2020 would be best

### Funding Source ###
164951 - JTTI Project, PI: Romine (Hank)
2770041 - JTTI Hail Project (Lindsay and Tina)

### Assignee ###
- [x ] Select **engineer(s)** or **no engineer** required
- [x ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x ] Select **component(s)**
- [x ] Select **priority**
- [x ] Select **requestor(s)**

### Projects and Milestone ###
- [ x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to other METplus components.
Related to [METplus Issue 405](https://github.com/NCAR/METplus/issues/405)
Related to [METplus Issue 406](https://github.com/NCAR/METplus/issues/406)
Related to [METplus Issue 413](https://github.com/NCAR/METplus/issues/413)

**Comment by lindsayrblank** [comment]
This issue has been done and we forgot to close it.
