### ISSUE TITLE
StatAnalysis wrapper silently fails when no field information is provided

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#422]
## Describe the Problem ##

This issue was first identified by a METplus user* who was running the StatAnalysis wrapper, then the MakePlots wrapper.  The MET stat_analysis tool is never run but the MakePlot wrapper is run and, as expected produces no plots.  When the StatAnalysis wrapper is run alone, then the MakePlots wrapper is run alone, no plots are being generated.  

*Refer to MET Help ticket #94784: 
       https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=94784

The VAR_LIST parameter has been replaced in the METplus 3.0 release and the StatAnalysis wrapper is still using this:
In stat_analysis_wrapper.py in create_c_dict() method:
        c_dict['VAR_LIST'] = util.parse_var_list(self.config)

When PROCESS_LIST=StatAnalysis,MakePlots there is a call to the filter_for_plotting() method in stat_analysis_wrapper.py that ensures MakePlots runs correctly following StatAnalysis.  In this method, the MET tool stat_analysis is never invoked because the var_info_list is empty:
------------snip-------------
# Loop through variables and add information
        # to a special variable dictionary
        for var_info in var_info_list:
--------------------------snip-------------

### Expected Behavior ###
When PROCESS_LIST=StatAnalysis, MakePlots the MET stat_analysis tool should be invoked and run successfully, creating output .stat file(s) based on the user's METplus config file.  The MakePlots wrapper should then be invoked and successfully create plots indicated by the METplus config file.

### Environment ###
Describe your runtime environment:
*1. Machine:  Unix (kiowa), cheyenne
*2. OS:  Debian Linux,  OS on cheyenne = ??
*3. METplus 3.0 + MET 9.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Get input for running StatAnalysis wrapper on host 'kiowa':
and unpack (see below for location)
*2. Using the settings in the METplus config file, make necessary changes to directory names (see below for location)
*3. Run master_metplus.py using your own custom.conf file
*4. Notice that there are no error messages in the log file, yet there are no .stat files or plot files created in the output directory

*Post relevant sample data following these instructions:*
     sample input data for StatAnalysis wrapper on 'kiowa':
    /d1/projects/METplus/BugFix_9478_Data/gstat_data.tar.gz 

    relevant METplus config file on host 'kiowa':
   /d1/projects/METplus/BugFix_9478_Data/StatAnalysis.conf

### Relevant Deadlines ###
6/15/2020 if possible

### Funding Source ###
2770471

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name: `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name: `bugfix_<Issue Number>_develop_<Description>`
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
c_dict['VAR_LIST'] is OK to use in this wrapper. This is different from the METplus config VAR_LIST, which has been replaced by calling met_util.parse_var_list. This function reads values from [FCST/OBS]\_VAR<n>\_[NAME/LEVELS/THRESH/OPTIONS] to determine which fields to process.

It looks like the StatAnalysis.conf file has FCST_VAR1 and OBS_VAR1 set. These should be set to FCST_VAR1_NAME and OBS_VAR1_NAME respectively. Changing these names causes StatAnalysis to run. This wrapper should have a check after the call to parse_var_list to check if this results in an empty list. If so, it should report a useful error.

However, changing these variable names still results in errors with MakePlots.

**Comment by georgemccabe** [comment]
This issue is more of an enhancement to improve the logging to alert the user if they are missing required configuration variables or have something misconfigured. Changing this ticket to Enhancement.

**Comment by georgemccabe** [comment]
It looks environment variables FCST_LEVEL and OBS_LEVEL are being set to '""' if they are not set via the config file, which is causing these arguments to be set instead of ignored.

FILTER:        -job filter -model CAMSiRA -fcst_lead 000000 -fcst_valid_beg 20180401_000000 -fcst_valid_end 20180501_210000 -fcst_valid_hour 000000 -fcst_valid_hour 030000 -fcst_valid_hour 060000 -fcst_valid_hour 090000 -fcst_valid_hour 120000 -fcst_valid_hour 150000 -fcst_valid_hour 180000 -fcst_valid_hour 210000 -fcst_var aermr04 -obs_var DUSTFINE **-fcst_lev  -obs_lev**  -obtype MERRA2_plv -vx_mask FULL -line_type SL1L2 -dump_row /d1/personal/mccabe/out/stat_analysis/CAMSiRA_MERRA2_plv_valid20180401to20180501_valid0000to2100Z_init0000to2359Z_fcst_lead000000_fcstaermr04_obsDUSTFINE_vxmaskFULL_dump_row.stat

These values should be set to an empty string if they are not set.

**Comment by georgemccabe** [comment]
Refactor of StatAnalysis/MakePlots wrappers and plotting_scripts include better handling of empty values so they are not added into the job list incorrectly. Also added better log error reporting and exiting when insufficient information is provided to the plotting scripts to avoid mysterious failures.
