### ISSUE TITLE
Develop new SWPC use case using_gen_vx_mask 

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METplus#427]
## Describe the New Feature ##
We need to develop a new use case for the SWPC project that illustrates the new gen_vx_mask wrapper capability that was developed in #387 and #424. The goal of this use case is to take a GloTEC model run and use gen_vx_mask to compute a mask for the region where solar altitude >= 60 deg (sun high in the sky). This could then be modified to do day-night masks or solar azimuthal angle.

### Acceptance Testing ###
Input: GloTEC netCDF files assimilated with and without COSMIC-1 Radio Occultation data
Test: Generate a time-varying mask for each model time level

### Time Estimate ###
8 hours (chargeable)

### Relevant Deadlines ###
No hard deadline. A good goal would be by April 21.

### Funding Source ###
2770471 - SWPC

### Assignee ###
- [x] Select **engineer** - George McCabe
- [x] Select **scientist** - Jonathan Vigh

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by jvigh** [comment]
I made some good progress on this use case (METplus #427). 
- I have prototyped the use case -- I am now debugging it. Currently, it doesn’t doesn’t seem to be reading the input file, even though I think the path is now correct. I’m guessing this might be because the GloTEC data are not fully CF-compliant. 
- The next step is to probably schedule a one-on-one with George.

**Comment by jvigh** [comment]
I've completed development. Am awaiting George's review.

**Comment by TaraJensen** [comment]
Awesome. Thanks

**Comment by georgemccabe** [comment]
Pull request approved, new use case is now being run in automated tests.
