### ISSUE TITLE
Update Tutorial Chapter 2 for MET 9, METplus 3.0

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#439]
Continue with MET/METplus updates passing to George and John for proofreading

**Comment by fentoad72** [comment]
Finished my go-through of Chapter 2, updated commands, config files, created additional exercise 2.1 where the user modifies the use_case PointStat.conf file and met_tool_wrapper file to illustrate how METplus interacts with MET

**Comment by georgemccabe** [comment]
Comment to test Todd's email filtering.

**Comment by TaraJensen** [comment]
I'm done with this chapter

**Comment by fentoad72** [comment]
Closed unless errors are found testing on supporting NCAR, NOAA platforms (#468)
