### ISSUE TITLE
Update Chapter 3 of the Tutorial

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#445]
Update Chapter 3 of the Monterrey Tutorial (July 2019) to reflect changes from METplus 2.2 to METplus 3.0

**Comment by fentoad72** [comment]
I've gone through Chapter 3.  Most changes are in the METplus section, and I'm not sure about the answers to Exercises 3.1 and 3.2 since the conf file contents and variable names may have changed

**Comment by TaraJensen** [comment]
I'm done with this Chapter

**Comment by fentoad72** [comment]
Closed unless errors are found testing on supporting NCAR, NOAA platforms (#468)
