### ISSUE TITLE
Add support to the METplus Dockerfile to build images based on specific branches

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#479]
This is a sub-issue of #478 

## Describe the Sub-Issue ##
Add support to the METplus Dockerfile to build images based on specific branches.
ie. develop image, a master_v3.0 image, bugfix image etc ...
And then update Docker Hub dtcenter/metplus to Build those images.

MET is building multiple images based on branches now for its Docker file ... good place to look for an example ...

Consider from the perspective of Travis support, Travis will be either building or pulling the Docker image from within a job.  Should be able to support both. ie. Travis job will know which branch it is running a build on (using travis environment variables) and than pull
or build appropriate Docker METplus image file. 

Consider  both the MET image and the METplus branch, when deciding/defining which images to build.

NOTE:
Each METplus docker image variant, REQUIRES a different FROM: line for MET
Need to investigate a solution.
Look at MET's Docker File as an example for ideas...
Multiple MET versions are created there ...use environment variables ...
Look in to passing additional arguments to the Docker build file (from travis.yml)
to define the MET Docker image that should be in the METplus Docker file
in line 1,  Instead of "FROM dtcenter/met:9.0" it should be an argument
passed in ...  FROM dtcenter/{COMMAND_LINE_ARG_FROM_TRAVIS}
Look at the MET Dockerfile for examples on passing in build args ...

NOTE: 
It seems reasonable for Feature branches, to continue using the dtcenter/metplus:develop image, vs. each feature branch creating their own respective feature images. Feature branch images, 99.9% of the time would be the same as the develop branch image anyway.
(but understand the implications, meaning if there was a change in the feature branch
that was directly needed in the Docker Hub image, it would not be available until pushed to develop). However, if you end up building the METplus Docker image within the Travis job, than this is moot since the branches METplus image will be built within the job and not
pulled from Docker Hub.

SIDE NOTE Consideration:
There was a discussion about adding Travis CI build support to the current master_v3.0 branch.
SHORT TERM QUICK OPTION FOR before adding multi-branch support:  You could support the building of master_v3.0 branch of METplus, by adding a branch specific travis.yml, Dockerfile and a README.md, that defines the required MET in the Dockerfile and
the travis settings to run on that branch.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by fentoad72** [comment]
taking over travis from jimfrimel

**Comment by georgemccabe** [comment]
Some of this work has already been completed by me. Currently the MET develop image is used in develop and feature branches. 

The MET image tag is also now controlled by a build arg (MET_VERSION). 

When a master_vX.Y release is created, we need to update the MET version to use the correct corresponding version (i.e. METplus 3.1 should use MET 9.1).

Task:
**We need to document all of the steps required to update the version and add it to the METplus release notes.**

**Comment by georgemccabe** [comment]
Closing this issue since the work has been completed. Created a new task for adding to the release instructions: #604
