### ISSUE TITLE
Add Multi branch Support to the Travis yml file

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#480]
This is a sub-issue of #478 

## Describe the Sub-Issue ##
Next, The travis build workflow itself needs 'logic' added to run and BUILD or PULL
different METplus Docker images (develop, master_v3.0, etc ...) based on the branch
it is running a build on.  (Implicit in this is also the proper MET image being used
in the METplus Dockerfile

- Add Multi branch Support to the travis.yml file
  This would be a straight forward conditional if block ...
  to make sure the desired docker image is pulled from docker hub,
  based on the current branch (or instead the docker image could be
  built by travis, rather than pulling it down).

HOWEVER: We do need to define ...
- Which branches should we support ?
  currently :develop
  Add :feature_+
  Add :master_v+
  Add :bugfix_

Note:.
Lastly Consider the "timing" issue which may be caused by pulling an Image from DockerHub. See: Sub-issue in the parent task.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by fentoad72** [comment]
taking over Travis from jimfrimel

**Comment by georgemccabe** [comment]
This work was done in preparation for the 3.1 release. @JohnHalleyGotway added a build hooks file to control the branch to use for the MET Docker image. I took that file and enhanced it to allow the user to specify the METplus branch and the MET branch to use.
