### ISSUE TITLE
Add Anaconda to METplus docker Images

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#484]
This is a sub-issue of #483 

## Describe the Sub-Issue ##
Install Anaconda within the METplus Docker image.

Note
This is not necessarily trivial and requires  investigation.
Ideally we do not want to build Anaconda from scratch in our Dockerfile,
we want to import an Anaconda image. Does continuum have one in DockerHub etc ..

Currently running python 3 (3.6.8) which is that latest that is available from the MET Dockerfile  and available via the yum installation.

Adding Anaconda will allow us to address these critical requirements:
 - Add Support for running MULTIPLE versions of Python in the docker image.
 - Will add support for running PLOTTING TESTS to Travis. Currently we can't run the
    plotting tests since we can't install the required packages in the current METplus image.
    Can't run pip install Cartopy in Dockerfile. Pandas , required plotting libs (version
    incompatibility)
 - This will add support for our environment.yml AND testingspecific python versions
    in METplus (3.6.x and 3.7).

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

**Comment by georgemccabe** [comment]
No longer needed
