### ISSUE TITLE
Add Automation to Deploy METplus Documentation to GitHub Pages.

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#487]
## Describe the Task ##

Add Automation to Deploy METplus Documentation to GitHub Pages.

The DOCS task in the current Travis yml is a placeholder and is to be
used as a staring point.

Carp the METpy/ci script and modify to meet METplus requirements.

Reference the METpy travis.yml DOCS sections and setup

METplus travis.yml DOCS section is only running doc8 (the opinionated style checker on the METplus documentations, and currently is is being forces to not return an error (an break the build) by running the true command since it returns a complaint

NOTE: Previous documentation versions are NOT rebuilt or re-deployed in (METpy)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travis from jimfrimel

**Comment by fentoad72** [comment]
change Travis-ci.org to travis-ci.com

**Comment by fentoad72** [comment]
If we change to ReadTheDocs, this issue could be closed because readthedocs automates it, but we'll need to create an issue to change the hard links to they don't point to github.io

**Comment by fentoad72** [comment]
This issue is changed because we're using ReadTheDocs and assigned to jprestop

If a ReadTheDocs issue exists; this can be closed.  If a ReadTheDocs issue does not exist, this issue can be modified to align to the current task plan.

**Comment by jprestop** [comment]
ReadTheDocs has been implemented and the documentation is being built via GitHub actions in all METplus component repositories.  This issue is being closed as it is no longer relevant.
