### ISSUE TITLE
Serve up the METplus development documentation through the MET website

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#49]
Write a script and run it through cron on mandan to clone the current development trunk from github and run make to generate the documentation.

Serve that documentation up by adding a link on this page:
http://www.dtcenter.org/met/users/docs/overview.php

Need to make sure that mandan has doxygen and git.

**Comment by georgemccabe** [comment]
We currently host the METplus documentation via ReadTheDocs: https://metplus.readthedocs.io
