### ISSUE TITLE
Documentation - Automatically generated version information

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#50]
One aspect of the following configure script, creates METplus version information displayed on the Doxygen generated METplus website.

METplus/sorc/doc/configure

It was originally designed to work with SVN. The version information is now
hard-coded in to a string in that file, since using Git.

### TASK:
The script needs  to be updated/ported to obtain the version Information from Git, so the
naming is automated ... once again.

**Comment by georgemccabe** [comment]
The version in documentation is read from the metplus/VERSION file. This can be closed.
