### ISSUE TITLE
Tutorial Proofreading (Keith)

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#534]
*Replace italics below with details for this issue.*

## Describe the Task ##
One more iteration through the tutorial material

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5

### Relevant Deadlines ###
7/21 or sooner

### Funding Source ###
none

### Assignee ###
ksearight
georgemccabe
fentoad72 (todd arbetter)

### Labels ###
- [ ] documentation
- [ ] medium

### Projects and Milestone ###
[Review tutorial text](https://dtcenter.org/metplus-practical-session-guide-version-3-0) for clarity (and spelling)
Leave notes in issue comments or [link to a Google Doc](https://docs.google.com/document/d/1jWOBwfRi5xtMGY4aV3qx_5vmdmq3N9xH9mUqH9L9uPc)

**Comment by ksearight** [comment]
Session 1 feedback is ready for review.

**Comment by fentoad72** [comment]
Hi Keith, can you provide an update?  Is this still in progress or can we mark it done?

**Comment by ksearight** [comment]
Still in progress and currently working on Chapter 2.
