### ISSUE TITLE
Generate PDF of User's Guide

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#551]
We have discussed generating a PDF of the User's Guide so users can access it offline. Also, many sponsors prefer print-out copies of documentation. I added an option to build the docs and generate a PDF copy.

To build a PDFs, you must have additional python packages (sphinx 2.4.2 or higher and rst2pdf) and set the environment variable METPLUS_DOC_PDF before running docs/build_docs.py.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)** (many)

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] Consider doing this for other projects

[MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by jprestop** [comment]
Reopening issue because while a PDF was created it is not formatted well enough to be released to the public.  We'd like to get the PDF in good shape so that it is acceptable to be released, but it needs some further work.

A build_docs.py script in the docs subdirectory has been created and currently recreates a PDF.

Users will need to set up the sphinx environment before running the docs/build_docs.py script and can do that on kiowa in the following way:
bash
conda deactivate
conda activate /home/met_test/.conda/envs/sphinx_env

This next line is for specifically creating the PDF file:
export METPLUS_DOC_PDF=1

**Comment by ksearight** [comment]
Here are PDFs I generated for the 4 METplus manuals.  @jprestop @georgemccabe How close do you think these are to being releasable?  
- [Verification_Datasets_Guide_vdevelop.pdf](https://github.com/dtcenter/METplus/files/6150311/Verification_Datasets_Guide_vdevelop.pdf)
- [METplus_Components_Release_Guide_vdevelop.pdf](https://github.com/dtcenter/METplus/files/6150315/METplus_Components_Release_Guide_vdevelop.pdf)
- [METplus_Contributers_Guide_vdevelop.pdf](https://github.com/dtcenter/METplus/files/6150316/METplus_Contributers_Guide_vdevelop.pdf)
- [METplus_Users_Guide_vdevelop.pdf](https://github.com/dtcenter/METplus/files/6150317/METplus_Users_Guide_vdevelop.pdf)  
  
Some issues:  
1. Need to increase the size of some of the images
2. No section/figure numbering
3. Long code blocks shrinks to really small font sizes
3. No index

**Comment by georgemccabe** [comment]
I just looked through the User's Guide and it looks pretty good! The formatting of the documentation for each use case is a little wonky, namely the use case config files that are added with a literal include of the file seem to be split up into multiple blocks with different sized text, but the content is all there. In my opinion, the docs are formatted very nicely on the web which is what most people will use, so I think it is OK if the formatting is a little off in the PDF as long as all of the content is there and correct.

**Comment by georgemccabe** [comment]
I also noticed some of the text is huge on page 19 of the User's Guide. I'm not sure why that happened.

**Comment by ksearight** [comment]
Per Tara, we need the section & figure numbers to release the PDFs.

**Comment by ksearight** [comment]
I've generated a PDF using ReadTheDocs in my feature_551_create_pdf_user_guide branch. 
[attached here](https://github.com/dtcenter/METplus/files/6183793/metplus-readthedocs-io-en-feature_551_create_pdf_user_guide.pdf).  I think it successfully addresses all the previously reported formatting issues from the command line build.
  
A few things I noticed:  
- Some of the numbering isn't indented correctly.  For example, in chapter 3.6, under Track and Intensity Use Case with Sample Data, the a, b, c, ... lines are flush with the numbered 1, 2, 3, ...
- The graphical links for the Use Cases under 5.1 are not shown.  The text for each of the links is correctly displayed.  The 3rd & 4th level numbering (e.g., 5.1.1 and 5.1.1.1) is not shown in the TOC at the top of the PDF.  The download links at the end of chapter 5.1 are not shown in the PDF.  The same issues are present for chapter 5.2 as well.
- None of the references in chapter 6 appear in the PDF in that chapter, but they are all listed in a new Bibliography chapter at the end.
- The PDF has an extra chapter 9 "Indices and tables" that has some bullets that don't link to anything, which could be confusing.
  
@georgemccabe @TaraJensen Please review the PDF and let me know how close you think this is to be ing releasable and the importance to address the above items (or others you find).  Feel free to tag others on the team to get their opinions (I know Julie is out on vacation this week).

**Comment by georgemccabe** [comment]
>     * Some of the numbering isn't indented correctly.  For example, in chapter 3.6, under Track and Intensity Use Case with Sample Data, the a, b, c, ... lines are flush with the numbered 1, 2, 3, ...

It looks like the indentation in the section above the Track and Intensity example is indented correctly. Perhaps this could be fixed by modifying the rst file?

>     * The graphical links for the Use Cases under 5.1 are not shown.  The text for each of the links is correctly displayed.  The 3rd & 4th level numbering (e.g., 5.1.1 and 5.1.1.1) is not shown in the TOC at the top of the PDF.  The download links at the end of chapter 5.1 are not shown in the PDF.  The same issues are present for chapter 5.2 as well.

I think it is OK that the thumbnails are not shown in the PDF. I do think it would be helpful to have at least the 3rd level numbering for these use cases in the table of contents if possible. There is a lot of content in that section so being able to quick go to a specific use case would be nice. We actually have scripting when we build the docs locally to remove the download links, so it is good that they are not rendered in the PDF. They are misleading and not useful. 

>     * None of the references in chapter 6 appear in the PDF in that chapter, but they are all listed in a new Bibliography chapter at the end.

That is odd. Did the Bibliography chapter get added automatically? I think it would be good to have the content in the chapter 6 if possible so that the PDF matches the web content.

>     * The PDF has an extra chapter 9 "Indices and tables" that has some bullets that don't link to anything, which could be confusing.

Is it possible to exclude this section from the PDF? I agree that it is confusing. The content is not really useful for the PDF, so it would be great if we can remove it. I did notice that on ReadTheDocs, the link to "Module Index" is actually a dead link. I'm not sure what it should contain. The "Index" link brings up a list of the glossary keywords that could be useful but I'm not sure it is completely necessary. On the web the "Search Page" link takes you to an empty search result, so I'm not sure that is necessary either.

> 
> 
> @georgemccabe @TaraJensen Please review the PDF and let me know how close you think this is to be ing releasable and the importance to address the above items (or others you find). Feel free to tag others on the team to get their opinions (I know Julie is out on vacation this week).

Chapter 7 contains quick search links that takes you to the website search results. The keyword links on each use case do as well. This may not be necessary for the PDF, but it is nice to be able to find all use cases that fit a specific category. I'm not sure how we would implement something like that for a PDF.

Other than the above items, I think the PDF is in pretty good shape!

**Comment by ksearight** [comment]
To Do list to finish the PDF version of the User Manual.
- [x] Some of the numbering isn't indented correctly. For example, in chapter 3.6, under Track and Intensity Use Case with Sample Data, the a, b, c, ... lines are flush with the numbered 1, 2, 3, ...
- [x] The Use Cases under 5.1 need to have at least the 3rd level numbering in the table of contents if possible.  _Done, except it's showing 5 levels for Ch. 5.  Haven't found a way to cut that back to 3 levels._
- [x] Prevent the references in chapter 6 from being moved to a new Bibliography chapter at the end.  
  _Partial Solution:  moved HTML References section to the end and eliminated the References section in the PDF.  The PDF references are still called Bibliography, but is in the same position in the document as the HTML version._
- [x] Exclude the extra chapter 9 "Indices and tables".
- [x] Chapter 7 contains quick search links that takes you to the website search results. The keyword links on each use case do as well. This may not be necessary for the PDF, but it is nice to be able to find all use cases that fit a specific category. I'm not sure how we would implement something like that for a PDF.  
  _I don't know of an easy way to implement this functionality in the PDF.  The searches could be run and the results inserted manually, which would be a large effort.  I added a warning message that appears only in the PDF version to alert the reader that the links are for online use._

**Comment by ksearight** [comment]
@georgemccabe @jprestop @TaraJensen Ready to review again and evaluate for doneness.  See the checklist above for the changes made.  The HTML version is changed as well as the PDF version.  Here are the RTD links to look at:  
- [HTML](https://metplus.readthedocs.io/en/feature_551_create_pdf_user_guide/)
- [PDF](https://metplus.readthedocs.io/_/downloads/en/feature_551_create_pdf_user_guide/pdf/)
  
If this passes muster, is the next step to merge in the changes from the develop branch?

**Comment by georgemccabe** [comment]
@ksearight I think it looks great!

Regarding Chapter 6 quick search links, if we were to add the actual keyword next to each of the links (i.e. the ASCII2NC link contains the keyword ASCII2NCToolUseCase in the URL), then the user could search for that string in the PDF to find the use cases that correspond to that quick search link. I noticed that you have additional text in the quick search page for the PDF only (Warning:The links in this section are used only with the online version of this user guide.) so if it is relatively easy to add the keyword text and a note saying to search for those keywords in the PDF, then that would accomplish the same behavior as the HTML quick search. The keyword is always between the text 'q=' and '&' so we could write a simple script to parse out that info and add it after the text. I'm not sure how others would feel about it but I would be OK with having the keyword next to the link text (separated by a : or -) in both versions for clarity and ease of implementation for the PDF.

**Comment by georgemccabe** [comment]
My only other comment would be to remove the lines in docs/conf.py that are from my previous attempt to generate a PDF so that there is no confusion as to what is needed to generate the version you created. There may be other files that I had changed that we will want to clean up as well (i.e. docs/Makefile a pdf directive was added that we should remove if it doesn't affect the generation of the new PDF).

@TaraJensen and @jprestop what are your thoughts on adding the actual quick search keywords next to each item so that users can search for those strings in the PDF to get the same behavior as the HTML quick search links?

Instead of:

Use Cases by MET Tool:
----------------------

[ASCII2NC](https://metplus.readthedocs.io/en/develop/search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default)
[CyclonePlotter](https://metplus.readthedocs.io/en/develop/search.html?q=CyclonePlotterUseCase&check_keywords=yes&area=default)
...


it would look like:

Use Cases by MET Tool:
----------------------

[ASCII2NC](https://metplus.readthedocs.io/en/develop/search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default): ASCII2NCToolUseCase
[CyclonePlotter](https://metplus.readthedocs.io/en/develop/search.html?q=CyclonePlotterUseCase&check_keywords=yes&area=default): CyclonePlotterUseCase
...


or

Use Cases by MET Tool:
----------------------

[ASCII2NC](https://metplus.readthedocs.io/en/develop/search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default) - ASCII2NCToolUseCase
[CyclonePlotter](https://metplus.readthedocs.io/en/develop/search.html?q=CyclonePlotterUseCase&check_keywords=yes&area=default) - CyclonePlotterUseCase
...


I'm open to different formatting as well.
Only the PDF would have a note at the top instructing the user to search the PDF for the keyword to find use cases that correspond to the quick search criteria.

**Comment by jprestop** [comment]
I think it's a good idea to remove the lines in docs/conf.py that are from George's previous attempt to generate a PDF so that there is no confusion.  @georgemccabe @ksearight I don't have any problems with adding the actual quick search keywords next to each item so that users can search for those strings in the PDF.  Keith, thank you so much for all of your work and effort on this!

**Comment by ksearight** [comment]
Thanks for your reviews.  I like the first option (with ":") for the keywords.  Let's do that.  I'll also look at some cleanup.

**Comment by ksearight** [comment]
Done!  I did see that the search links are also in the entries in Chapter 5, so those may need to be changed as well.  Those are pointing to the pre-RTD locations, so I suggest creating a new issue to change them.
