### ISSUE TITLE
Valid thresholds incorrectly fail error check

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#558]
Jamie Wolff discovered that valid thresholds with letters, i.e. >SFP90, are incorrectly denied due to error checking that expects a threshold value to be a comparison operator (i.e. < or ge) following by a number.

## Describe the Problem ##
Thresholds with numbers should be allowed.

### Expected Behavior ###
validate_thresholds function should return True if the input list includes >SFP90.

### Environment ###
Any Linux workstation with METplus available

### To Reproduce ###
On kiowa:
cd /d1/projects/METplus/METplus_test_environments/thresholds/METplus.develop
conda activate /home/met_test/.conda/envs/metplus_base

python
from metplus.util import validate_thresholds
good_list = ['>=5.4', 'lt72']
should_be_good_list = ['>=5.4', 'lt72', '>SFP90']
validate_thresholds(good_list)
validate_thresholds(should_be_good_list)
quit()

Verify 2nd validate_thresholds command returns False

Now repeat the python steps with the bugfix branch.

cd /d1/projects/METplus/METplus_test_environments/thresholds/METplus.bugfix_558

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_558_validate_thresholds`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>**.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
There are a handful of threshold type strings which fall into this category (**SFP, SOP, SCP, USP, FBIAS, and CDP**), all of which should be allowed.
Below is an excerpt taken from: https://ncar.github.io/MET/Users_Guide/data_io.html

- The following percentile threshold types are supported:
         - "SFP" for a percentile of the sample forecast values.
           e.g. ">SFP50" means greater than the 50-th forecast percentile.
         - "SOP" for a percentile of the sample observation values.
           e.g. ">SOP75" means greater than the 75-th observation percentile.
         - "SCP" for a percentile of the sample climatology values.
           e.g. ">SCP90" means greater than the 90-th climatology percentile.
         - "USP" for a user-specified percentile threshold.
           e.g. "<USP90(2.5)" means less than the 90-th percentile values which
           the user has already determined to be 2.5 outside of MET.
         - "==FBIAS1" to automatically de-bias the data. This option must be
           used in conjunction with a simple threshold in the other field.
           For example, when "obs.cat_thresh = >5.0" and
           "fcst.cat_thresh = ==FBIAS1;", MET applies the >5.0 threshold to the
           observations and then chooses a forecast threshold which results in a
           frequency bias of 1.
         - "CDP" for climatological distribution percentile thresholds.
           These thresholds require that the climatological mean and standard
           deviation be defined using the climo_mean and climo_stdev config file
           options, respectively. The categorical (cat_thresh), conditional
           (cnt_thresh), or wind speed (wind_thresh) thresholds are defined
           relative to the climatological distribution at each point. Therefore,
           the actual numeric threshold applied can change for each point.
           e.g. ">CDP50" means greater than the 50-th percentile of the
           climatological distribution for each point.
