### ISSUE TITLE
docker push pull image repository

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#639]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
*Investigate whether docker updates after every build, and if updated it should push to metplus-dev*
update Test use cases to pull from metplus_dev:develop instead of building a new image

### Time Estimate ###
*Estimate the amount of work required here.*
1-2 dats

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
I've gone over the code and tried different ways of entering my Docker credentials and it looks like my permissions aren't set to write to dtcenter/METplus-dev.  If I use dtcenter/METplus the code pulls, builds, and pushes dtcenter/METplus:develop in docker_setup.sh and then in the use cases pulls down the existing dtcenter/METplus:develop image (doesn't rebuild it every time).

**Comment by JohnHalleyGotway** [comment]
Todd,

Just checked and saw that the METplus “team” had admin access on the
METplus repo but no permissions in METplus-dev.

So I just changed them to match the METplus permissions.

Please try again.

John

**Comment by fentoad72** [comment]
Looks like everything's working now, pushing and pulling from dtcenter/METplus-dev.  Thanks for being a nite owl, John!

**Comment by JohnHalleyGotway** [comment]
Todd,

Great glad to hear it. You know we currently don’t have any permissions
defined on METplus-data or METplus-data-dev and have admin defined for
METplus and METplus-dev.

I wonder if read/write for all those repos for the METplus “team” would be
the right choice?

John

**Comment by fentoad72** [comment]
I guess it's a question of how many people should have write access.  If they don't, they can still pull the images down as long as they have read access, the idea being they can pull down a pre-built image rather than have to build a new one every time, which was the goal of the Github issue I'm working on.

Some timing: it takes 1m 35sec to download dtenter/METplus-dev:develop, the METplus docker image.  It takes 0-3 secs to build it because it recognizes that dtcenter:MET:develop (the MET docker image) hasn't changed so doesn't need to be pulled.  And it takes 3 seconds to push dtcenter/METplus-dev:develop back to the repo because little or nothing has changed.  If/when the MET image changes, or the dependencies, it will download the new ones, but until then, it's basically a couple minutes per use case to download the latest image, then whatever it takes to go through the use case tests.  We've shaved off a few minutes per use case, and there's probably a way to combine different use cases that combine to less than 50 minutes and reduce the overall time for the travis build.  But that's another Github issue....

**Comment by georgemccabe** [comment]
This issue was resolve by PR #646 because changes in this branch were needed for other development. A new issue was created for the timing tests (#649) to ensure that these changes are improving the timing of Travis jobs.
