### ISSUE TITLE
different file system between MET source code by git and by download

### ISSUE THREAD

**Issue by linyu0219** [dtcenter/METplus#666]
git clone  MET and download source code (met9.1.tar.gz) on MET'release page has different files.
like 'met/src/basic/vx_math/viewgravity_to_string.cc'   in tar.gz but not in git.
when  metplus build met by git clone by userguide, it  will  have compile error.

**Comment by linyu0219** [comment]
metplus 3.1

**Comment by JohnHalleyGotway** [comment]
Linyu, this is not a bug. The default branch of MET is named main_v9.1. It contains the MET version 9.1 release plus all bugfixes for met-9.1. Once we’ve accumulated enough bugfixes, we’ll create a met-9.1.1 bugfix release from that branch. In addition, the code in the tarfile will never exactly equal the code in the repo. When creating a release, a couple of automatic code generation tools are run. The viewgravity_to_string.cc file is an example of one of those.

Users should only be compiling code from the tarfile. Developers can compile the code directly from repository. However the MET_DEVELOPMENT environment variable must be set... I usually just set it to “true”. And that triggers the configure script to run those automatic code generation tools.

FYI, here is the list of the bugfixes that have not yet been included in a release:

https://github.com/dtcenter/MET/milestone/68?closed=1
