### ISSUE TITLE
Document Continous Integration Functionality in the METplus Contributor's Guide

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#675]
*Replace italics below with details for this issue.*

## Describe the Task ##
Document what is done with Travis.yml and Docker in the repo for versioning, testing, building, etc., for those that don't know Travis.  Eventually this would be a chapter in the Contributor's Guide

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Potential topics include:
-- how to read and write a travis.yml file (and what it does)
-- the Travis webpage/gui
-- travis CLI: what is useful, such as travis log (cross-post with Travis CLI Github Issue)
-- github-travis-docker setup and interaction
-- using Travis (or "Pass") to store credentials

**Comment by fentoad72** [comment]
I wrote up [5 pages on Travis](https://docs.google.com/document/d/1-SWAPQVI53bN5ilGFmU8cyl3zBxMifr7m7pvaUaVKdI/edit) and how it works, including walking through the METplus travis.yml file.

Please comment directly in the document.  I think it could be fleshed out in a number of ways, including doing a little research on Circle CI and Github Actions (Circle CI is credit based, while GItHub Actions remains fee to open-source, with limitations)

**Comment by georgemccabe** [comment]
@fentoad72 , I quickly reviewed the doc and there is a lot of good information in it. I added a few comments of which sections to expand (details about the scripts). I also recommended that you add code blocks in the final doc for each section of the .travis.yml file you describe so it is easier to follow.
