### ISSUE TITLE
Add the METplus Development Git Workflow document

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#73]
As discussed in the MET meeting, start/add the simplified development workflow
document to the source code document directory. Provide a Reference link to
this document from the github wiki.

The document is intended to provide a simplified reference of the git commands 
to use (by everyone, Scientists and Engineers) for various workflows in the METplus 
development cycle of the master, develop, featureX branches 

The "prompt>" format of this document is meant to explicitly represent the branch
you are currently on when issuing the git command.

For example,

local-only feature branch development cycle
--------------------------------------------
* The feature branch will only exist on your local machine, not on GitHub
(In Git jargon: No remote tracking of feature branch)

master> git checkout develop
develop> git checkout -b featureX
featureX> ... make changes, commit, test ...
featureX> git checkout develop
develop> git pull
develop> git merge featureX
develop> .. test ...
develop> git push origin develop

**Comment by georgemccabe** [comment]
This exists in the Contributor's Guide (we no longer use the GitHub wiki) here: https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html
