### ISSUE TITLE
Fix EnsembleStat wrapper config glossary items

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#828]
## Describe the Problem ##
While working on #768 I noticed some issues with the following three METplus conf items in the glossary:
OBS_ENSEMBLE_STAT_INPUT_GRID_DATATYPE
ENS_ENSEMBLE_STAT_INPUT_DATATYPE
FCST_ENSEMBLE_STAT_INPUT_DATATYPE

1. Is the first one supposed to be *GRID_DATAYPE? Or just *_DATATYPE?
2. It appears item 2 is not in the conf glossary
3. Double check item 3 is correct in glossary

### Expected Behavior ###
*Provide a clear and concise description of what you expected to happen here.*

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
Additionally, should these be "DATATYPE", or "FILETYPE" to more closely align with MET vernacular? It seems like for EnsembleStat, there is a METPLUS_ENS_FILE_TYPE which controls the setting of the file_type item in the ens dictionary in the MET config file, but this is controlled via METplus using a conf item with "DATATYPE" in the name (ENS_ENSEMBLE_STAT_DATATYPE).

**Comment by georgemccabe** [comment]
OBS_ENSEMBLE_STAT_INPUT_GRID_DATATYPE is correct. EnsembleStat supports grid obs and point obs, so there are different variables for each.

**Comment by DanielAdriaansen** [comment]
@georgemccabe would you agree this was handled via #768 and this issue can be closed?

**Comment by georgemccabe** [comment]
I would double check that items 2 and 3 were completed, then close the ticket if they are. If not, we will need to move this to 4.1.0-beta1.

**Comment by DanielAdriaansen** [comment]
Looks like number 2 and number 3 are in the glossary reviewed as part of #903 so I am closing this issue. Thanks George.
